---
pagetitle: "WomensExposure"
nb-authors:
  - Brayden Youngberg
  - Shalika Vyas
execute:
  echo: false
---

```{ojs}
import { heroImage } from "/helpers/hero.js";
hero_url = "./../../images/womenClimate.webp";

hero = heroImage(nbTitle, hero_url);
html`${hero}`;
```

```{ojs}
import { atlasTOC } from '/helpers/toc.ojs' 
{
  await nbText // force wait/reload with nbText to load so headings have correct labels/languages
  return atlasTOC({
      heading: `<b>${_lang({en:"In this notebook", fr:"Dans ce notebook"})}</b>`,
      skip: [nbTitle, "notebook-title", "Appendix", "source-code"]
      })
}
```

# `{ojs} nbTitle` {class='title' #notebook-title}

```{ojs}
viewof prettyLanguageView = {
  return Inputs.bind(
    Inputs.radio(languages, {
      label: _lang({en: "Language", fr: "Langue"}),
      format: (d) => d.label
    }),
    viewof language
  );
}
```

# `{ojs} Overview` {#overview}

`{ojs} _lang(nbText.overview.text)`

# `{ojs} AgIsGendered` {#AgIsGendered}

`{ojs} _lang(nbText.GenderedAfriAG.text)`

### `{ojs} _lang(nbText.GenderedAfriAG.FemaleParticipationLabor.title)`

```{ojs}
//| echo: true
//| code-fold: true
//| code-summary: "View plot code"
plotHeatmapParticipation = {
  const data = task_gender_data;

  const margin = { top: 30, right: 0, bottom: 5, left: 90 };
  const width = 475 
  const height = 250

  const tooltip = d3
    .select("body")
    .append("div")
    .attr("class", "plotTooltip")
    .style("position", "absolute");

  const svg = d3
    .create('svg')
    .attr("viewBox", [
      0,
      0,
      width + margin.left + margin.right,
      height + margin.top + margin.bottom
    ])
    // .attr("width", "%")
    .attr("height", "100%");

  const xScale = d3
    .scaleBand()
    .domain(data.map((d) => d.country))
    .range([margin.left, width - margin.right])
    .padding(0.05);

  const yScale = d3
    .scaleBand()
    .domain(["Land Prep.", "Planting/Weeding", "Harvesting"])
    .range([margin.top, height - margin.bottom])
    .padding(0.05);

  // const colorScale = d3.scaleSequential(d3.interpolateBlues).domain([0, 100]);
  const colorScale = d3
    .scaleLinear()
    .domain([21, 61])
    .range(["#F7D732", "#216729"]);

  svg
    .selectAll("rect")
    .data(
      data.flatMap((d) =>
        ["Land Prep.", "Planting/Weeding", "Harvesting"].map((type) => ({
          country: d.country,
          type,
          value: d[type]
        }))
      )
    )
    .join("rect")
    .attr("x", (d) => xScale(d.country))
    .attr("y", (d) => yScale(d.type))
    .attr("width", xScale.bandwidth())
    .attr("height", yScale.bandwidth())
    .attr("fill", (d) => (d.value !== null ? colorScale(d.value) : "white")) // Set fill to white for null values
    .on("mousemove", (event, d) => {
      tooltip
        .style("top", event.pageY - 10 + "px")
        .style("left", event.pageX + 10 + "px")
        .style("opacity", 1)
        .html(
          `${_lang(nbText.General.adminNames[d.country])}<br>${_lang(nbText.GenderedAfriAG.FemaleParticipationLabor.plot.practices[d.type])}: ${
            d.value !== null ? d.value + "%" : _lang(nbText.General.noDataAvailable)
          }`
        );
    })
    .on("mouseout", function (event, d) {
      tooltip.style("opacity", 0);
    });

  svg
    .append("g")
    .attr("transform", `translate(0, ${height - margin.bottom})`)
    .attr("stroke-width", ".5px")
    .call(d3.axisBottom(xScale).tickFormat((d) => _lang(nbText.General.adminNames[d])))
    .selectAll("text")
    .style("font-size", "8px");

  const yAxis = svg
    .append("g")
    .attr("transform", `translate(${margin.left}, 0)`)
    .attr("stroke-width", ".5px")
    .call(d3.axisLeft(yScale).tickFormat((d) => (_lang(nbText.GenderedAfriAG.FemaleParticipationLabor.plot.practices[d]))))
    .selectAll("text")
    .style("font-size", "8px");

  svg
    .append("g")
    .attr("transform", `translate(85,-10) scale(0.70)`)
    .append(heatmap_legend);

  return svg.node();
}
```

`{ojs} downloadButton(task_gender_data, "FemaleAgLaborParticipation", _lang(nbText.General.download))`

## `{ojs} _lang(nbText.GenderedAfriAG.WomenDominate.title)`

`{ojs} _lang(nbText.GenderedAfriAG.WomenDominate.text)`

`{ojs} genderCropHeadline()`

```{ojs}
genderCropHeatmap = {
//| echo: true
//| code-fold: true
//| code-summary: "View plot code"
  const data = crop_gender_data;

  const margin = { top: 40, right: 0, bottom: 5, left: 100 };
  const width = 475 
  const height = 320

  const tooltip = d3
    .select("body")
    .append("div")
    .attr("class", "plotTooltip")
    .style("position", "absolute");

  const svg = d3
    .create("svg")
    .attr("viewBox", [
      0,
      0,
      width + margin.left + margin.right,
      height + margin.top + margin.bottom
    ])
    // .attr("width", "85%")
    .attr("height", "90%");

  const xScale = d3
    .scaleBand()
    .domain(data.map((d) => d.country))
    .range([margin.left, width - margin.right])
    .padding(0.05);

  const yScale = d3
    .scaleBand()
    .domain([
      "Cereals",
      "Legumes",
      "Roots & Tubers",
      "Fruits & Vegetables",
      "Non-edible crops"
    ])
    .range([margin.top, height - margin.bottom])
    .padding(0.05);

  // const colorScale = d3.scaleSequential(d3.interpolateBlues).domain([0, 100]);
  const colorScale = d3
    .scaleLinear()
    .domain([21, 61])
    .range(["#F7D732", "#216729"]);

  svg
    .selectAll("rect")
    .data(
      data.flatMap((d) =>
        [
          "Cereals",
          "Legumes",
          "Roots & Tubers",
          "Fruits & Vegetables",
          "Non-edible crops"
        ].map((type) => ({
          country: d.country,
          type,
          value: d[type]
        }))
      )
    )
    .join("rect")
    .attr("x", (d) => xScale(d.country))
    .attr("y", (d) => yScale(d.type))
    .attr("width", xScale.bandwidth())
    .attr("height", yScale.bandwidth())
    .attr("fill", (d) => (d.value !== null ? colorScale(d.value) : "white"))
    .on("mouseover", function (event, d) {
      mutable hover_data = d;
    })
    .on("mousemove", (event, d) => {
      tooltip
        .style("top", event.pageY - 10 + "px")
        .style("left", event.pageX + 10 + "px")
        .style("opacity", 1)
        .html(
          `${_lang(nbText.General.adminNames[d.country])}<br>${_lang(nbText.GenderedAfriAG.FemaleParticipationCrops.plot.crops[d.type])}: ${
            d.value !== null ? d.value + "%" : _lang(nbText.General.noDataAvailable)
          }`
        );
    })
    .on("mouseout", function (event, d) {
      mutable hover_data = null;
      tooltip.style("opacity", 0);
    });

  svg
    .append("g")
    .attr("transform", `translate(0, ${height - margin.bottom})`)
    .attr("stroke-width", ".5px")
    .call(d3.axisBottom(xScale).tickFormat((d) => _lang(nbText.General.adminNames[d])))
    .selectAll("text")
    .style("font-size", "8px");

  svg
    .append("g")
    .attr("transform", `translate(${margin.left}, 0)`)
    .attr("stroke-width", ".5px")
    .call(d3.axisLeft(yScale).tickFormat((d) => _lang(nbText.GenderedAfriAG.FemaleParticipationCrops.plot.crops[d])))
    .selectAll("text")
    .style("font-size", "8px");

  svg
    .append("g")
    .attr("transform", `translate(100,-10) scale(0.75)`)
    .append(heatmap_legend);

  return svg.node();
}
```

`{ojs} DownloadButton(crop_gender_data, "FemaleCropParticipation", _lang(nbText.General.download))`

# `{ojs} GenderInvestments` {#genderInvestments}

`{ojs} _lang(nbText.GenderInvestments.text)`

`{ojs} admin_form()`

## `{ojs} _lang(nbText.GenderInvestments.title)`

```{ojs}
//| echo: true
//| code-fold: true
//| code-summary: "View plot code"

genderInvestmentLollipop = {
  const margin = { top: 10, right: 70, bottom: 35, left: 85 };
  const width = 350 - margin.left - margin.right;
  const height = 200 - margin.top - margin.bottom;

  const lollipop_admin = admin1_sel === "Full Country" ? _lang(nbText.General.adminNames[country]) : admin1_sel;

  const tooltip = d3
    .select("body")
    .append("div")
    .attr("class", "plotTooltip")
    .style("position", "absolute");

  let tooltipText;
  if (admin1_sel !== "Full Country") {
    tooltipText = (d) =>
      `${_lang(nbText.GenderInvestments.GenderIndex.plot.domains[d])}<br>${lollipop_admin} ${_lang(nbText.General.mean)}: ${filteredData[d].toFixed(
        2
      )}<br>${region_name} ${_lang(nbText.General.mean)}: ${regional_avg[d].toFixed(2)}`;
  } else {
    tooltipText = (d) =>
      `${_lang(nbText.GenderInvestments.GenderIndex.plot.domains[d])}<br>${lollipop_admin} ${_lang(nbText.General.mean)}: ${filteredData[d].toFixed(
        2
      )}`;
  }

  const svg = d3
    .create("svg")
    .attr("viewBox", [
      0,
      0,
      width + margin.left + margin.right,
      height + margin.top + margin.bottom
    ])
    .attr("width", "90%")
    .attr("height", "90%");

  const g = svg
    .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

  const data = roi[0];
  const variablesToKeep = [
    "empowerment_index",
    "decisions",
    "domestic_violence",
    "education",
    "employment",
    "family_planning",
    "reproductive_health"
  ];
  const filteredData = Object.fromEntries(
    Object.entries(data).filter(([key, value]) => variablesToKeep.includes(key))
  );

  const variables = Object.keys(filteredData);
  variables.sort(
    (a, b) => variablesToKeep.indexOf(a) - variablesToKeep.indexOf(b)
  );

  const region_name =
    country === "SSA" || admin1_sel === "Full Country" ? "SSA" : country;

  const xScale = d3.scaleLinear().domain([0, 1]).range([0, width]);

  const yScale = d3
    .scaleBand()
    .domain(variables)
    .range([0, height])
    .padding(0.1);

  let countryLine_offset = 2;

  if (admin1_sel !== "Full Country") {
    countryLine_offset = 2.75;
    const meanLine_offset = 1.5;

    const meanLine = g
      .selectAll(".mean-line")
      .data(variables)
      .enter()
      .append("line")
      .attr("class", "mean-line")
      .attr("x1", 0)
      .attr("x2", (d) => xScale(regional_avg[d]))
      .attr(
        "y1",
        (d) => yScale(d) + yScale.bandwidth() / meanLine_offset
      )
      .attr(
        "y2",
        (d) => yScale(d) + yScale.bandwidth() / meanLine_offset
      )
      .attr("stroke", "grey")
      .attr("stroke-width", 0.75);

    meanLine
      .on("mousemove", (event, d) => {
        tooltip
          .style("top", event.pageY - 10 + "px")
          .style("left", event.pageX + 10 + "px")
          .style("opacity", 1)
          .html(tooltipText(d));
      })
      .on("mouseout", function (event, d) {
        tooltip.style("opacity", 0);
      });

    const meanDot = g
      .selectAll(".mean-dot")
      .data(variables)
      .enter()
      .append("circle")
      .attr("class", "mean-dot")
      .attr("cx", (d) => xScale(regional_avg[d]))
      .attr(
        "cy",
        (d) => yScale(d) + yScale.bandwidth() / meanLine_offset
      )
      .attr("r", 2)
      .attr("fill", "grey");

    meanDot
      .on("mousemove", (event, d) => {
        tooltip
          .style("top", event.pageY - 10 + "px")
          .style("left", event.pageX + 10 + "px")
          .style("opacity", 1)
          .html(tooltipText(d));
      })
      .on("mouseout", function (event, d) {
        tooltip.style("opacity", 0);
      });
    g.append("g")
      .attr("transform", `translate(195, 70) scale(0.35)`)
      .append(loli_legend);
  }

  const line = g
    .selectAll(".line")
    .data(variables)
    .enter()
    .append("line")
    .attr("class", "line")
    .attr("x1", 0.1)
    .attr("x2", (d) => xScale(filteredData[d]))
    .attr(
      "y1",
      (d) => yScale(d) + yScale.bandwidth() / countryLine_offset
    )
    .attr(
      "y2",
      (d) => yScale(d) + yScale.bandwidth() / countryLine_offset
    )
    .attr("stroke", "#57832b")
    .attr("stroke-width", 0.75);

  line
    .on("mousemove", (event, d) => {
      tooltip
        .style("top", event.pageY - 10 + "px")
        .style("left", event.pageX + 10 + "px")
        .style("opacity", 1)
        .html(tooltipText(d));
    })
    .on("mouseout", function (event, d) {
      tooltip.style("opacity", 0);
    });

  const dot = g
    .selectAll(".dot")
    .data(variables)
    .enter()
    .append("circle")
    .attr("class", "dot")
    .attr("cx", (d) => xScale(filteredData[d]))
    .attr(
      "cy",
      (d) => yScale(d) + yScale.bandwidth() / countryLine_offset
    )
    .attr("r", 3)
    .attr("fill", "#57832b");

  dot
    .on("mousemove", (event, d) => {
      tooltip
        .style("top", event.pageY - 10 + "px")
        .style("left", event.pageX + 10 + "px")
        .style("opacity", 1)
        .html(tooltipText(d));
    })
    .on("mouseout", function (event, d) {
      tooltip.style("opacity", 0);
    });

  g.append("g")
    .attr("transform", `translate(0,${height})`)
    .call(d3.axisBottom(xScale))
    .attr("stroke-width", ".5px")
    .attr("font-size", "8px");

  g.append("text")
    .attr("transform", `translate(${width / 2}, ${height + margin.bottom - 5})`)
    .style("text-anchor", "middle")
    .text(_lang(nbText.GenderInvestments.GenderIndex.plot.title_X))
    .attr("font-size", "8px");

  g.append("g")
    .call(d3.axisLeft(yScale).tickSize(0).tickFormat((d) => _lang(nbText.GenderInvestments.GenderIndex.plot.domains[d])))
    .attr("stroke-width", ".5px")
    .attr("font-size", "8px");

  return svg.node();
}
```

`{ojs} DownloadButton(non_topo, "FemaleEmpowerment", _lang(nbText.General.download))`

# `{ojs} GenderHotspots` {#genderHotspots}

`{ojs} _lang(nbText.GenderHotspots.text)`

```{ojs}
viewof BiVariable_form = Inputs.form(
  {
    hazard: Inputs.radio(["human", "crop", "livestock"], {
      value: "human",
      label: html`<span style="width: 0px; display: flex;align-items: center;white-space: nowrap;">${_lang(nbText.GenderHotspots.selectors.heatHazard.title)}</span>`,
      format: (x) =>
        html`<div style="display: flex; align-items: center; padding: 0px; margin-top: -5px">
      ${hs_icons[x].cloneNode(true)} <span style="margin-left: 5px;">${_lang(nbText.GenderHotspots.selectors.heatHazard.hazards[x])}</span>
    </div>`
    }),
    Gender_var: Inputs.bind(
      Inputs.select(
        Object.keys(F_dict),
        {
          label: _lang(nbText.GenderHotspots.selectors.GenderVar.title),
          value: "women_in_agric",
          format: (x) => _lang((nbText.GenderHotspots.selectors.GenderVar.domains[x]))
        }
      ),
      viewof sel_gender_var
    )
  },
  {
    template: (
      inputs
    ) => htl.html`<div style="display: flex; align-items: flex-start; gap: 3em">
  ${Object.values(inputs)}
</div>`
  }
)

viewof bivar_form = Inputs.form(
  {
    country: Inputs.bind(
      Inputs.select(a0_list, {
        label: _lang(nbText.General.country),
        value: clickedAdmin0,
        format: (v) => _lang(nbText.General.adminNames[v]) 
      }),
      viewof country
    ),
    scenario: Inputs.select(
      Object.keys(scenario_dict),
      {
        label: _lang(nbText.General.scenario),
        format: (x) => x === "historic" ? _lang(nbText.General.historic) : scenario_dict[x]
      }
    )
  },
  {
    template: (inputs) => htl.html`<div style="display: flex; gap: 3em">
  ${Object.values(inputs)}
</div>`
  }
)
```

```{ojs}
//| echo: true
//| code-fold: true
//| code-summary: "View plot code"
BivariateMap = () => {
  const height = 610;
  const width = 775;
  const padding = 20;

  let x;

  if (country === "SSA") {
    x = d3.scaleQuantile(
      Array.from(
        BiVar_merge.filter((d) => d.admin1_name === null),
        (d) => d[G_variable]
      ),
      d3.range(3)
    );
  } else {
    x = d3.scaleQuantile(
      Array.from(
        BiVar_merge.filter((d) => d.admin1_name !== null),
        (d) => d[G_variable]
      ),
      d3.range(3)
    );
  }

  const haz_threshold = [
    hazard_bivariate_thresholds[heat_hazard]["low"],
    hazard_bivariate_thresholds[heat_hazard]["high"]
  ];

  d3.select(".bivariateTip").remove();
  const tooltip = d3
    .select("body")
    .append("div")
    .attr("class", "plotTooltip bivariateTip")
    .style("position", "absolute");

  const y = d3.scaleThreshold().domain(haz_threshold).range(d3.range(3));

  const projection = d3.geoMercator();

  const geo_path = d3.geoPath().projection(projection);
  const color = d3.scaleOrdinal().domain(d3.range(9)).range(bi_color);

  const a0_features = topojson.feature(
    admin0_boundaries,
    admin0_boundaries.objects["atlas-region_admin0_harmonized"]
  );

  projection.fitExtent(
    [
      [padding, padding],
      [width - padding, height - padding]
    ],
    a0_features
  );

  const svg = d3
    .create("svg")
    .attr("viewBox", [0, 0, 900, 680])
    .attr("title", "Map")
    .on("dblclick", resetView);

  const a0_paths = svg
    .append("g")
    .selectAll("path")
    .data(a0_features.features)
    .join("path")
    .attr("stroke", "white")
    .attr("stroke-width", "1px")
    .attr("class", "admin0-boundary")
    .attr("fill", (d) => {
      const a0_data = index.get(d.properties.admin0_name).get(null);
      return color(x(a0_data[G_variable]) * 3 + y(a0_data.hs_value));
    })
    .attr("d", geo_path)
    .on("click", clicked);

  a0_paths
    .on("mousemove", (event, d) => {
      tooltip
        .style("top", event.pageY - 10 + "px")
        .style("left", event.pageX + 10 + "px")
        .style("opacity", 1)
        .html(() => {
          const admin0_name = d.properties.admin0_name;
          const dataEntry = index.get(admin0_name).get(null);
          
          const heatStressText = `${_lang(nbText.GenderHotspots.plot.heatLabels[heat_hazard])}: ${dataEntry.hs_value.toFixed(
            2
          )} (${_lang(nbText.General[labels[y(dataEntry.hs_value)]])})`;
          let variableText;
          if (G_variable === "women_in_agric") {
            variableText = `${_lang(nbText.GenderHotspots.selectors.GenderVar.domains[G_variable])}: ${dataEntry[
              G_variable
            ].toLocaleString(undefined, { maximumFractionDigits: 0 })} (${
              _lang(nbText.General[labels[x(dataEntry[G_variable])]])
            })`;
          } else {
            variableText = `${_lang(nbText.GenderHotspots.selectors.GenderVar.domains[G_variable])}: ${dataEntry[
              G_variable
            ].toFixed(2)} (${_lang(nbText.General[labels[x(dataEntry[G_variable])]])})`;
          }
          return `${_lang(nbText.General.adminNames[admin0_name])}<br>${heatStressText}<br>${variableText}`;
        });
    })
    .on("mouseout", function (event, d) {
      mutable hover_data = null;
      tooltip.style("opacity", 0);
    });

  const mesh = svg
    .append("path")
    .datum(
      topojson.mesh(
        admin0_boundaries,
        admin0_boundaries.objects["atlas-region_admin0_harmonized"],
        (a, b) => a !== b
      )
    )
    .attr("fill", "none")
    .attr("stroke", "black")
    .attr("stroke-linejoin", "round")
    .attr("d", geo_path);

  if (clickedAdmin0 !== null) {
    const padding_a1 = 150;
    const admin1_features = topojson
      .feature(
        admin1_boundaries,
        admin1_boundaries.objects["atlas-region_admin1_harmonizedV2"]
      )
      .features.filter(
        (feature) => feature.properties.admin0_name === clickedAdmin0
      );

    const admin1_geojson = {
      type: "FeatureCollection",
      features: admin1_features
    };

    const a1_paths = svg
      .append("g")
      .selectAll("path")
      .data(admin1_features)
      .join("path")
      .attr("stroke", "white")
      .attr("stroke-width", "1px")
      .attr("fill", (d) => {
        const admin0_map = index.get(d.properties.admin0_name);
        const a1_data = admin0_map.get(d.properties.admin1_name);
        return color(x(a1_data[G_variable]) * 3 + y(a1_data.hs_value));
      })
      .attr("class", "admin1-boundary");

    a1_paths
      .on("mousemove", (event, d) => {
        tooltip
          .style("top", event.pageY - 10 + "px")
          .style("left", event.pageX + 10 + "px")
          .style("opacity", 1)
          .html(() => {
            const dataEntry = index
              .get(d.properties.admin0_name)
              .get(d.properties.admin1_name);
            const heatStressText = `${_lang(nbText.GenderHotspots.plot.heatLabels[heat_hazard])}: ${dataEntry.hs_value.toFixed(
              2
            )} (${_lang(nbText.General[labels[y(dataEntry.hs_value)]])})`;
            let variableText;
            if (G_variable === "women_in_agric") {
              variableText = `${_lang(nbText.GenderHotspots.selectors.GenderVar.domains[G_variable])}: ${dataEntry[
                G_variable
              ].toLocaleString(undefined, { maximumFractionDigits: 0 })} (${
                _lang(nbText.General[labels[x(dataEntry[G_variable])]])
              })`;
            } else {
              variableText = `${_lang(nbText.GenderHotspots.selectors.GenderVar.domains[G_variable])}: ${dataEntry[
                G_variable
              ].toFixed(2)} (${_lang(nbText.General[labels[x(dataEntry[G_variable])]])})`;
            }
            return `${d.properties.admin1_name}, ${_lang(nbText.General.adminNames[d.properties.admin0_name])}<br>${heatStressText}<br>${variableText}`;
          });
      })
      .on("mouseout", function (event, d) {
        mutable hover_data = null;
        tooltip.style("opacity", 0);
      });

    projection.fitExtent(
      [
        [padding_a1, padding_a1],
        [width - padding_a1, height - padding_a1] // This is where the translate happens + 250
      ],
      admin1_geojson
    );

    a0_paths.attr("visibility", "hidden");
    svg.selectAll("path").attr("d", geo_path);
  }

  const legend = svg
    .append("g")
    .attr("transform", `translate(-30,${height - 210}) scale(1)`)
    .append(bi_legend);

  return svg.node();

  function resetView() {
    mutable clickedAdmin0 = null;
    projection.fitExtent(
      [
        [padding, padding],
        [width - padding, height - padding]
      ],
      a0_features
    );
    svg.selectAll("path").attr("d", geo_path);
  }

  function clicked(event, d) {
    mutable clickedAdmin0 = d.properties.admin0_name;
  }
}

BivariateMap()
```

`{ojs} biVar_insight()`

# `{ojs} BridgeGap` {#bridgeGap}

`{ojs} _lang(nbText.BridgeGap.text)`

```{ojs}
viewof adaptation = Inputs.select(adaptationOptions, {
  label: _lang(nbText.BridgeGap.selector.title),
  format: (l) =>  _lang(nbText.BridgeGap.selector.options[l])
})
```

```{ojs}
//| echo: true
//| code-fold: true
//| code-summary: "View table code"
{
  const columns = [
    "Sector",
    "Gender Outcome Score",
    "Geography",
    "Confidence in Result",
    "Risk"
  ];

  const table_data = gender_solutions.filter(
    (d) => d["Adaptation Options"] === adaptation
  );

  let table = `
  <style>
          .tableTooltip::after {
            content: attr(data-tooltip);
            position: absolute;
            transform: translateX(1%);
            background: rgba(255,255,255,0.95);
            color: #333;
            border: 1px solid #333;
            padding: 10px; 
            border-radius: 5px;
            opacity: 0;
            pointer-events: none;
            transition: opacity 0.5s;
            z-index: 1;
        }

        .tableTooltip:hover::after {
            opacity: 1;
        }
    td, th {
      border-right: 1px solid lightgray;
      color: black;
    }

  </style><table style="table-layout: fixed; min-height: 100%; min-width: 85%; font-size: 13px;"><thead><tr style="background-color:  #CCC;">${columns
    .map(
      (c) =>
        `<th style="padding: 10px; height: 40px; vertical-align: middle;" >${_lang(nbText.BridgeGap.table.headings[c])}</th>`
    )
    .join("")}</tr></thead><tbody>`;

  for (let [index, row] of table_data.entries()) {
    let rowColor = index % 2 === 0 ? "#f2f2f2" : "#ffffff";
    table += `<tr style="background-color: ${rowColor};">${columns
      .map((c) => {
        if (c === "Gender Outcome Score" && row[c]) {
          let outcome = row[c];
          let sign = "";
          let tipText;
          if (outcome === "Enabling") {
            sign = `<span style="color: lightgreen; font-weight: bold; font-size: 16px; ">+</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.enable);
          } else if (outcome === "Reinforcing") {
            sign = `<span style="color: #57832b; font-weight: bold; font-size: 16px; ">+</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.reinforce);
          } else if (outcome === "Constraining") {
            sign = `<span style="color: orange; font-weight: bold; font-size: 16px; ">-</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.constrain);
          } else {
            sign = `<span style="color: red; font-weight: bold; font-size: 16px; ">-</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.counteract);
          }
          return `<td style="vertical-align: middle;padding: 0 20px;">
          <span class="tableTooltip" data-tooltip="${tipText}">${sign} ${_lang(nbText.BridgeGap.table.values[row[c].toLowerCase()])}</span>
        </td>`;
        } else if (c === "Geography" && row[c]) {
          return `<td style="vertical-align: middle;padding: 3px 20px;">${row[c]
            .split(",")
            .map((country) =>
              country_flags[country.trim()]
                ? `<span class="tableTooltip" data-tooltip="${_lang(nbText.General.adminNames[country.trim()])}">${
                    country_flags[country.trim()].outerHTML
                  }</span>`
                : country
            )
            .join(" ")}</td>`;
        } else if (c === "Risk" && row[c]) {
          return `<td style="vertical-align: middle;padding: 0 20px;">${row[c]
            .split(",")
            .map((risk) =>
              climate_risk_icons[risk.trim()]
                ? `<span class="tableTooltip" data-tooltip="${_lang(nbText.BridgeGap.table.tooltip[risk.trim().toLowerCase()])}" style="margin-right: 10px;">${
                    climate_risk_icons[risk.trim()].outerHTML
                  }</span>`
                : risk
            )
            .join(" ")}</td>`;
        } else if (c === "Confidence in Result" && row[c]) {
          let agreementColor;
          if (row[c] === "High") {
            agreementColor = "green";
          } else if (row[c] === "Medium") {
            agreementColor = "orange";
          } else {
            agreementColor = "red";
          }
          return `<td style="vertical-align: middle; padding: 0 15px">
                   <div style="display: flex; align-items: center;">
                     <div style="background-color: ${agreementColor}; height: 10px; width: 20px; margin-left: 10px; margin-right: 10px; border-radius: 20%;"></div>
                     <div>${_lang(nbText.BridgeGap.table.values[row[c].toLowerCase()])}</div>
                   </div>
                  </td>`;
        } else {
          return `<td style="vertical-align: middle;padding: 0 20px;">
${row[c].split(", ").map((v) => _lang(nbText.BridgeGap.table.values[v.toLowerCase()])).join(", ")}
          </td>`;
        }
      })
      .join("")}</tr>`;
  }

  table += `</tbody></table>`;

  let tableContainer = `<div style="max-height: 100%;">${table}</div>`;

  return html`${tableContainer}`;
}
```

# `{ojs} Summary` {#summary}

`{ojs} _lang(nbText.Summary.text)`

# Source code {#source-code .hidden}

## Text translations and language support

```{ojs}
nbTitle = _lang({
  en: "Analyze Women's Exposure to Climate Hazards",
  fr: "Analyser l'exposition des femmes aux aléas climatiques",
});
// h1
Overview = _lang(nbText.overview.title);
AgIsGendered = _lang(nbText.GenderedAfriAG.title);
GenderInvestments = _lang(nbText.GenderInvestments.title);
GenderHotspots = _lang(nbText.GenderHotspots.title);
BridgeGap = _lang(nbText.BridgeGap.title);
Summary = _lang(nbText.Summary.title);

// h2
WomenDominate = _lang(nbText.GenderedAfriAG.WomenDominate.title);
FemaleParticipation = _lang(
  nbText.GenderedAfriAG.FemaleParticipationLabor.title,
);
```

```{ojs}
nbText = await FileAttachment("/data/genderNotebook/Gender_nbText.json").json()

import { lang as Lang } from "/helpers/lang.js"

_lang = await Lang.lg(language.key)

defaultLangKey = {
  const list = languages.map((d) => d.key);
  const defaultKey = "en";
  const queryParam = await Lang.getParamFromList({ name: "lang", list });
  return queryParam ?? defaultKey;
}

languages = [
  { key: "en", label: "English", locale: 'en-US' },
  { key: "fr", label: "Français", locale: 'fr-FR' }
]

viewof language = Inputs.radio(languages, {
  label: "Main language toggle",
  format: (d) => d.key,
  value: languages.find((x) => x.key === defaultLangKey),
})
```

## Notebook Data Import

```{ojs}
// Primary DB
db = {
  const db = await DuckDBClient.of({
    gender: FileAttachment("/data/genderNotebook/a0a1_gender_variables.parquet"),
    hazards: FileAttachment("/data/genderNotebook/HS_hazards.parquet"),
    mapspam_vop: FileAttachment("/data/genderNotebook/mapspam_vop.parquet")
  });
  return db;
}


// Heatmap Data
task_gender_data = FileAttachment("/data/genderNotebook/task_gender_data.json").json()
crop_gender_data = FileAttachment("/data/genderNotebook/crop_gender_data.json").json()
crop_groups = FileAttachment("/data/genderNotebook/crop_groups.json").json()
crop_gender_means = FileAttachment("/data/genderNotebook/crop_gender_means.json").json()

// Admin Data
admin1_boundaries = FileAttachment(
  "/data/genderNotebook/atlas-region_admin1_harmonizedV2.json"
).json()

admin0_boundaries = FileAttachment("/data/genderNotebook/atlas-region_admin0_simplified.json").json()

// Solutions

gender_solutions = FileAttachment("/data/genderNotebook/gender_solutions.json").json()
```

## Boundary Selection and delivery

```{ojs}
a0_list = ["SSA"].concat(
  Array.from(
    new Set(
      Object.values(
        admin0_boundaries.objects["atlas-region_admin0_harmonized"].geometries
      ).map((d) => d.properties.admin0_name)
    )
  )
)

a1_list = {
  const filteredData = admin1_boundaries.objects[
    "atlas-region_admin1_harmonizedV2"
  ].geometries.filter((d) => d.properties.admin0_name === country);

  const a1Names = Array.from(
    new Set(filteredData.map((d) => d.properties.admin1_name))
  );
  return ["Full Country"].concat(a1Names);
}

mutable clickedAdmin0 = null

viewof country = {
  // Create the selection input.
  const country = Inputs.select(a0_list, {
    // label: html`<b>Select Country:</b>`,
    label: "Select Country",
    value: clickedAdmin0
  });

  // Update clickedAdmin0 when the selection changes.
  country.addEventListener("input", () => {
    mutable clickedAdmin0 = country.value === "SSA" ? null : country.value;
  });
  return country;
}

viewof admin1_sel = Inputs.select(a1_list, { label: "admin1" })

admin_form = () => {
  return Inputs.form(
    [
      Inputs.bind(Inputs.select(a0_list, { label: _lang(nbText.General.country), format: (v) => _lang(nbText.General.adminNames[v]) }), viewof country),
      Inputs.bind(
        Inputs.select(a1_list, { label: _lang(nbText.General.region), format: (v) => v === "Full Country" ? _lang(nbText.General.adminNames[v]): v }),
        viewof admin1_sel
      )
    ],
    {
      template: (inputs) =>
        htl.html`<div style="display: flex; gap: 3em">${inputs}</div>`
    }
  );
}
```

## Notebook Helpers

```{ojs}
import { downloadButton } from "/helpers/uiComponents.ojs";

formatDollar = new Intl.NumberFormat("en-US", {
  notation: "compact",
  compactDisplay: "short",
  style: "currency",
  currency: "usd",
}).format;
```

## Dictionaries

```{ojs}
F_dict = new Object({
  women_in_agric: "Women in Agriculture",
  empowerment_index: "Empowerment Index",
  education: "Education",
  domestic_violence: "Domestic Safety",
  reproductive_health: "Reproductive Health",
  family_planning: "Family Planning",
  employment: "Employment",
  decisions: "Decision Making",
});

hazard_dict = new Object({
  human: "HSH",
  crop: "NTx35",
  livestock: "THI",
});

hazard_bivariate_thresholds = new Object({
  human: { low: 27, high: 42 },
  livestock: { low: 72, high: 90 },
  crop: { low: 9, high: 25 },
});

scenario_dict = new Object({
  historic: "Historic",
  ssp245: "SSP245",
  ssp585: "SSP585",
});
```

## Backend Section: AgIsGendered

### Heatmap Legend

```{ojs}
heatmap_legend = () => {
  const svg = d3.create("svg").attr("width", 200).attr("height", 60);

  const defs = svg.append("defs");
  const linearGradient = defs
    .append("linearGradient")
    .attr("id", "linear-gradient");

  linearGradient
    .attr("x1", "0%")
    .attr("y1", "0%")
    .attr("x2", "100%")
    .attr("y2", "0%");

  linearGradient
    .append("stop")
    .attr("offset", "0%")
    .attr("stop-color", "#F7D732");
  linearGradient
    .append("stop")
    .attr("offset", "100%")
    .attr("stop-color", "#216729");

  svg
    .append("rect")
    .attr("width", 100)
    .attr("height", 15)
    .style("fill", "url(#linear-gradient)")
    .attr("transform", "translate(15,30)");

  const legendScale = d3.scaleLinear().range([0, 100]).domain([0, 1]);

  const legendAxis = d3
    .axisTop()
    .scale(legendScale)
    .tickValues([0, 1])
    .tickFormat((d) =>
      d === 0
        ? _lang(nbText.GenderedAfriAG.LegendScale.low)
        : _lang(nbText.GenderedAfriAG.LegendScale.high),
    )
    .tickSize(0);

  svg
    .append("g")
    .attr("class", "legend axis")
    .attr("transform", "translate(15,30)")
    .call(legendAxis)
    .style("font-size", "10px");

  svg.selectAll(".axis path").style("stroke", "none");

  return svg.node();
};
```

### Women Dominate Section

#### Data

```{ojs}
mutable hover_data = null

root_tube_total = {
  const total = await db.query(
    `SELECT SUM("value") as rt_sum, admin0_name
     FROM "mapspam_vop"
     WHERE crop IN (${crop_groups["Roots & Tubers"]})
     GROUP BY admin0_name`
  );

  const women_total = total.map((d) => {
    const match = crop_gender_data.find((item) => item.country === d.admin0_name);
    return match && match['Roots & Tubers'] ? d.rt_sum * (match['Roots & Tubers']/100) : null;
  });

  const sum_W_total = women_total.reduce((acc, val) => acc + (val || 0), 0)
  

  return sum_W_total;
}

crop_cat = {
  if (hover_data === null) {
    return null;
  } else {
    return hover_data.type;
  }
}

selection_total = {
  if (crop_cat === null) {
    return null;
  } else {
    const total = await db.query(
      `Select  SUM("value") as crop_sum
  FROM mapspam_vop
  WHERE admin0_name LIKE '%${hover_data.country}'
  AND crop in (${crop_groups[crop_cat]})`
    );
    return Math.round(total[0]["crop_sum"]);
  }
}

gender_data = db.query(`Select *
  FROM gender`)

hazard_data = db.query(`Select admin0_name, admin1_name, scenario, timeframe as time, value as hs_value, hazard
  FROM hazards
  WHERE hazard LIKE '%${hazard_dict[heat_hazard]}%'
  AND admin2_name IS NULL`)
```

#### Dynamic Headline

```{ojs}
genderCropHeadline = () => {
  const container = html`<div style="height: 120px; overflow: hidden;">`;
  let text;
  let fill_items;

  if (hover_data === null) {
    text = md`${_lang(nbText.GenderedAfriAG.WomenDominate.headline.default)}`;
  } else if (hover_data.value !== null) {
    const involvementLevel =
      hover_data.value > crop_gender_means["country_mean"][hover_data.country]
        ? "more"
        : "less";
    const productionValue = formatDollar(
      selection_total * (hover_data.value / 100),
    );
    fill_items = [
      {
        name: "country",
        value: _lang(nbText.General.article_adminNames[hover_data.country]),
      },
      { name: "involvement", value: _lang(nbText.General[involvementLevel]) },
      {
        name: "cropType",
        value: _lang(
          nbText.GenderedAfriAG.FemaleParticipationCrops.plot.crops[
            hover_data.type
          ],
        ),
      },
      { name: "cropPCT", value: hover_data.value },
      { name: "cropValue", value: productionValue },
    ];
    let template = _lang(
      nbText.GenderedAfriAG.WomenDominate.headline.valid_hover,
    );
    text = md`${Lang.reduceReplaceTemplateItems(template, fill_items)}`;
  } else {
    let template = _lang(
      nbText.GenderedAfriAG.WomenDominate.headline.null_hover,
    );
    fill_items = [
      {
        name: "country",
        value: _lang(nbText.General.article_adminNames[hover_data.country]),
      },
      {
        name: "cropType",
        value: _lang(
          nbText.GenderedAfriAG.FemaleParticipationCrops.plot.crops[
            hover_data.type
          ],
        ),
      },
    ];
    text = md`${Lang.reduceReplaceTemplateItems(template, fill_items)}`;
  }
  return text;
};
```

## Backend Section: GenderInvestments

### Data

```{ojs}
roi = {
  function calculateMeanVariables(raw_data) {
    return raw_data.reduce((acc, obj) => {
      Object.keys(obj).forEach((key) => {
        if (typeof obj[key] === "number" && !isNaN(obj[key])) {
          acc[key] = (acc[key] || 0) + obj[key] / raw_data.length;
        }
      });
      return acc;
    }, {});
  }
  let roiData;
  if (country !== "SSA") {
    if (admin1_sel === "Full Country" || admin1_sel === null) {
      const raw_data = non_topo.filter((d) => d.admin0_name === country);
      roiData = [calculateMeanVariables(raw_data)];
    } else {
      roiData = non_topo.filter((d) => d.admin1_name === admin1_sel);
    }
  } else {
    roiData = [calculateMeanVariables(non_topo)];
  }
  return roiData;
}

regional_avg = {
  const surrounding = non_topo.filter((d) => d.admin1_name !== "na");

  const variablesToKeep = [
    "decisions",
    "domestic_violence",
    "education",
    "employment",
    "family_planning",
    "empowerment_index",
    "reproductive_health"
  ];

  // Calculate the mean value for each variable
  const meanValues = variablesToKeep.reduce((acc, variable) => {
    const sum = surrounding.reduce((sum, area) => sum + area[variable], 0);
    acc[variable] = sum / surrounding.length;
    return acc;
  }, {});

  return meanValues;
}

non_topo = {
  if (country === "SSA" || admin1_sel === "Full Country") {
    return db.query(`SELECT * FROM gender`);
  } else {
    return db.query(`SELECT * FROM gender WHERE admin0_name LIKE '${country}'`);
  }
}
```

### lolipop Legend

```{ojs}
loli_legend = () => {
  const svg = d3.create("svg").attr("width", 200).attr("height", 100);

  const box = svg
    .append("rect")
    .attr("width", 200)
    .attr("height", 100)
    .attr("rx", 10)
    .attr("ry", 10)
    .attr("fill", "#f0f0f0");

  const color = d3
    .scaleOrdinal()
    .domain(["Regional average", "Admin average"])
    .range(["#216729", "grey"]);

  const circles = svg
    .selectAll("circle")
    .data(["Regional average", "Admin average"])
    .join("circle")
    .attr("cx", 30)
    .attr("cy", (d, i) => 35 + i * 30)
    .attr("r", 6)
    .attr("fill", (d) => color(d));

  let region_name;
  if (admin1_sel !== "Full Country") {
    region_name = admin1_sel;
  }

  const labels = svg
    .selectAll("text")
    // .data([region_name + " average", country + " average"])
    .data(["regional_avg", "national_avg"])
    .join("text")
    .attr("x", 45)
    .attr("y", (d, i) => 40 + i * 30)
    .text((d) => _lang(nbText.General[d]));

  return svg.node();
};
```

## Backend Section: GenderHotspots

### Data

```{ojs}
labels = ["low", "moderate", "high"]
index = d3.index(
  BiVar_merge,
  (d) => d.admin0_name,
  (d) => d.admin1_name
)

BiVar_merge = {
  // const hazard_regex = /(_mean$ |/i;
  const filtered_haz = hazard_data.filter(
    (d) =>
      d.scenario === ssp && //Note the ! operator i nnext line
      !d.hazard.includes("mean") && // could be mean or max
      (d.time === "2041_2060" || d.time === "historic")
    // d.admin1_name !== null //hazard_regex.test(d.hazard)
  );
  const mergedData = filtered_haz.map((item2) => {
    const matchingItem = gender_data.find(
      (item1) =>
        item1["admin0_name"] === item2["admin0_name"] &&
        item1["admin1_name"] === item2["admin1_name"]
    );

    return matchingItem ? { ...matchingItem, ...item2 } : item2;
  });

  return mergedData;
}

filtered_haz = hazard_data.filter(
  (d) => d.scenario === 'historic' && !d.hazard.includes("max") //&&
  // d.admin1_name !== null //hazard_regex.test(d.hazard)
)
```

### Selectors

```{ojs}
viewof sel_gender_var = Inputs.select(
  new Map(Object.entries(F_dict).map(([key, value]) => [value, key])),
  { label: "Variable", value: "women_in_agric" }
)

ssp = bivar_form["scenario"]
heat_hazard = BiVariable_form["hazard"]
G_variable = BiVariable_form["Gender_var"]
```

### Bivariate Map

##### Legend

```{ojs}
bi_color = {
  if (G_variable === "women_in_agric") {
    return [
      "#e8e8e8",
      "#e4acac",
      "#c85a5a",
      "#b0d5df",
      "#ad9ea5",
      "#985356",
      "#64acbe",
      "#627f8c",
      "#574249"
    ];
  } else {
    return [
      "#e8e8e8",
      "#ddb395",
      "#d17a3d",
      "#a7c4d4",
      "#a7b395",
      "#a77a3d",
      "#65a0bf",
      "#65a095",
      "#657a3d"
    ];
  }
}

bi_legend = () => {
  const k = 50;
  const arrow = "arrow-id";
  d3.select(".biLegend").remove();
  const tooltip = d3
    .select("body")
    .append("div")
    .attr("class", `plotTooltip biLegend`)
    .style("position", "absolute")
    .style("opacity", 0);

  const svg = d3
    .create("svg")
    .attr("width", 500) // increased size
    .attr("height", 500) // increased size
    .attr("viewBox", "0 0 525 525") // increased viewBox
    .attr("font-family", "sans-serif")
    .attr("font-size", 10);
  //

  const g = svg
    .append("g")
    .attr(
      "transform",
      `rotate(-45 ${(k * 3) / 2},${(k * 3) / 2}) translate(50, 100)`
    );

  g.append("marker")
    .attr("id", arrow)
    .attr("markerHeight", 10)
    .attr("markerWidth", 10)
    .attr("refX", 6)
    .attr("refY", 3)
    .attr("orient", "auto")
    .append("path")
    .attr("d", "M0,0L9,3L0,6Z");

  d3.cross(d3.range(3), d3.range(3)).forEach(([i, j]) => {
    const x = i * k;
    const y = (3 - 1 - j) * k;
    const fillColor = bi_color[j * 3 + i];
    const titleText = `${_lang(nbText.GenderHotspots.selectors.GenderVar.domains[G_variable])}: ${_lang(nbText.General[labels[j]])}<br>${_lang(nbText.GenderHotspots.plot.heatLabels[heat_hazard])}: ${_lang(nbText.General[labels[i]])}`;

    g.append("rect")
      .attr("width", k)
      .attr("height", k)
      .attr("x", x)
      .attr("y", y)
      .attr("fill", fillColor)
      .on("mousemove", (event, d) => {
        tooltip
          .style("top", event.pageY - 10 + "px")
          .style("left", event.pageX + 1 + "px")
          .style("opacity", 1)
          .html(titleText);
      })
      .on("mouseout", function (event, d) {
        mutable hover_data = null;
        tooltip.style("opacity", 0);
      });
  });

  g.append("line")
    .attr("marker-end", `url(#${arrow})`)
    .attr("x1", 0)
    .attr("x2", 3 * k)
    .attr("y1", 3 * k)
    .attr("y2", 3 * k)
    .attr("stroke", "black")
    .attr("stroke-width", 1.5);

  g.append("line")
    .attr("marker-end", `url(#${arrow})`)
    .attr("y2", 0)
    .attr("y1", 3 * k)
    .attr("stroke", "black")
    .attr("stroke-width", 1.5);

  g.append("text")
    // .attr("font-weight", "bold")
    .attr("font-size", "13px")
    .attr("dy", "0.71em")
    .attr("transform", `rotate(90) translate(${(3 / 2) * k},6)`)
    .attr("text-anchor", "middle")
    .text(_lang(nbText.GenderHotspots.selectors.GenderVar.domains[G_variable]));

  g.append("text")
    // .attr("font-weight", "bold")
    .attr("font-size", "13px")
    .attr("dy", "0.71em")
    .attr("transform", `translate(${(3 / 2) * k},${3 * k + 6})`)
    .attr("text-anchor", "middle")
    .text(_lang(nbText.GenderHotspots.plot.heatLabels[heat_hazard]));

  return svg.node();
}
```

### Bivariate Insight

```{ojs}
biVar_insight = () => {
  let filtered =
    country === "SSA"
      ? BiVar_merge.filter((d) => d.admin1_name === null).map((d) => ({
          ...d,
          admin_name: d.admin0_name,
        }))
      : BiVar_merge.filter(
          (d) => d.admin0_name === country && d.admin1_name !== null,
        ).map((d) => ({ ...d, admin_name: d.admin1_name }));

  const heat_HotSpot = filtered.reduce(
    (max, obj) =>
      obj.hs_value > max.hs_value
        ? {
            admin_name: obj.admin_name,
            hs_value: obj.hs_value,
            ac_value: obj[G_variable],
          }
        : max,
    { admin_name: null, hs_value: -Infinity },
  );

  const classifyHSValue = (value) => {
    const thresholds = hazard_bivariate_thresholds[heat_hazard];
    return value < thresholds.low
      ? "low"
      : value <= thresholds.high
        ? "moderate"
        : "high";
  };

  const classifyACValue = (value) => {
    const values =
      country === "SSA"
        ? BiVar_merge.filter((d) => d.admin1_name === null).map(
            (d) => d[G_variable],
          )
        : BiVar_merge.filter((d) => d.admin1_name !== null).map(
            (d) => d[G_variable],
          );
    const val_class = d3.scaleQuantile(values, d3.range(3))(value);
    return val_class === 0 ? "low" : val_class === 1 ? "moderate" : "high";
  };

  const gender_HotSpot = filtered.reduce(
    (extreme, obj) =>
      G_variable === "women_in_agric"
        ? obj[G_variable] > extreme.value
          ? {
              admin_name: obj.admin_name,
              value: obj[G_variable],
              hs_value: obj.hs_value,
            }
          : extreme
        : obj[G_variable] < extreme.value
          ? {
              admin_name: obj.admin_name,
              value: obj[G_variable],
              hs_value: obj.hs_value,
            }
          : extreme,
    G_variable === "women_in_agric"
      ? { admin_name: null, value: -Infinity }
      : { admin_name: null, value: Infinity },
  );
  let classified_ac = classifyACValue(heat_HotSpot.ac_value);
  let classified_hs = classifyHSValue(gender_HotSpot.hs_value);

  let regionIntro =
    country === "SSA" ? { en: "", fr: "" } : { en: "", fr: "la region de" };
  let regionIntro_cap =
    country === "SSA" ? { en: "", fr: "" } : { en: "", fr: "La region de" };
  let template_fillers = [
    {
      name: "country",
      value: _lang(nbText.General.article_adminNames[country]),
    },
    { name: "regionIntro", value: _lang(regionIntro) },
    { name: "regionIntro_cap", value: _lang(regionIntro_cap) },
    {
      name: "highest_gender",
      value: translateA0_only(gender_HotSpot.admin_name),
    },
    {
      name: "HS_level",
      value: _lang(
        nbText.GenderHotspots.dynamicLevels[classified_hs.toLowerCase()],
      ),
    },
    {
      name: "heatstress_var",
      value: _lang(
        nbText.GenderHotspots.plot.heatLabels[heat_hazard],
      ).toLowerCase(),
    },
    { name: "highest_hs", value: translateA0_only(heat_HotSpot.admin_name) },
    {
      name: "AC_level",
      value: _lang(
        nbText.GenderHotspots.dynamicLevels[classified_ac.toLowerCase()],
      ),
    },
  ];
  let md_text;
  let template;
  if (G_variable === "women_in_agric") {
    template = _lang(nbText.GenderHotspots.dynamicInsight_womenInAgri);
  } else {
    template_fillers.push({
      name: "gender_var",
      value: _lang(nbText.GenderHotspots.domains[G_variable]).toLowerCase(),
    });
    template = _lang(nbText.GenderHotspots.dynamicInsight_FEMI);
  }

  return md`${Lang.reduceReplaceTemplateItems(template, template_fillers)}`;

  function translateA0_only(adminName) {
    const translatedName = _lang(nbText.General.article_adminNames[adminName]);
    return translatedName === undefined ? adminName : translatedName;
  }
};
```

## Backend Section: BridgeGap

### Data

```{ojs}
adaptationOptions = Array.from(
  new Set(gender_solutions.map((d) => d["Adaptation Options"])),
);
```

### Table

```{ojs}
tableHTML = () => {
  const columns = [
    "Sector",
    "Gender Outcome Score",
    "Geography",
    "Confidence in Result",
    "Risk",
  ];

  const table_data = gender_solutions.filter(
    (d) => d["Adaptation Options"] === adaptation,
  );

  let table = `
  <style>
          .tableTooltip::after {
            content: attr(data-tooltip);
            position: absolute;
            transform: translateX(1%);
            background: rgba(255,255,255,0.95);
            color: #333;
            border: 1px solid #333;
            padding: 10px; 
            border-radius: 5px;
            opacity: 0;
            pointer-events: none;
            transition: opacity 0.5s;
            z-index: 1;
        }

        .tableTooltip:hover::after {
            opacity: 1;
        }
    td, th {
      border-right: 1px solid lightgray;
      color: black;
    }

  </style><table style="table-layout: fixed; min-height: 100%; min-width: 85%; font-size: 13px;"><thead><tr style="background-color:  #CCC;">${columns
    .map(
      (c) =>
        `<th style="padding: 10px; height: 40px; vertical-align: middle;" >${_lang(nbText.BridgeGap.table.headings[c])}</th>`,
    )
    .join("")}</tr></thead><tbody>`;

  for (let [index, row] of table_data.entries()) {
    let rowColor = index % 2 === 0 ? "#f2f2f2" : "#ffffff";
    table += `<tr style="background-color: ${rowColor};">${columns
      .map((c) => {
        if (c === "Gender Outcome Score" && row[c]) {
          let outcome = row[c];
          let sign = "";
          let tipText;
          if (outcome === "Enabling") {
            sign = `<span style="color: lightgreen; font-weight: bold; font-size: 16px; ">+</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.enable);
          } else if (outcome === "Reinforcing") {
            sign = `<span style="color: #57832b; font-weight: bold; font-size: 16px; ">+</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.reinforce);
          } else if (outcome === "Constraining") {
            sign = `<span style="color: orange; font-weight: bold; font-size: 16px; ">-</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.constrain);
          } else {
            sign = `<span style="color: red; font-weight: bold; font-size: 16px; ">-</span>`;
            tipText = _lang(nbText.BridgeGap.table.tooltip.counteract);
          }
          return `<td style="vertical-align: middle;padding: 0 20px;">
          <span class="tableTooltip" data-tooltip="${tipText}">${sign} ${_lang(nbText.BridgeGap.table.values[row[c].toLowerCase()])}</span>
        </td>`;
        } else if (c === "Geography" && row[c]) {
          return `<td style="vertical-align: middle;padding: 3px 20px;">${row[c]
            .split(",")
            .map((country) =>
              country_flags[country.trim()]
                ? `<span class="tableTooltip" data-tooltip="${_lang(nbText.General.adminNames[country.trim()])}">${
                    country_flags[country.trim()].outerHTML
                  }</span>`
                : country,
            )
            .join(" ")}</td>`;
        } else if (c === "Risk" && row[c]) {
          return `<td style="vertical-align: middle;padding: 0 20px;">${row[c]
            .split(",")
            .map((risk) =>
              climate_risk_icons[risk.trim()]
                ? `<span class="tableTooltip" data-tooltip="${_lang(nbText.BridgeGap.table.tooltip[risk.trim().toLowerCase()])}" style="margin-right: 10px;">${
                    climate_risk_icons[risk.trim()].outerHTML
                  }</span>`
                : risk,
            )
            .join(" ")}</td>`;
        } else if (c === "Confidence in Result" && row[c]) {
          let agreementColor;
          if (row[c] === "High") {
            agreementColor = "green";
          } else if (row[c] === "Medium") {
            agreementColor = "orange";
          } else {
            agreementColor = "red";
          }
          return `<td style="vertical-align: middle; padding: 0 15px">
                   <div style="display: flex; align-items: center;">
                     <div style="background-color: ${agreementColor}; height: 10px; width: 20px; margin-left: 10px; margin-right: 10px; border-radius: 20%;"></div>
                     <div>${_lang(nbText.BridgeGap.table.values[row[c].toLowerCase()])}</div>
                   </div>
                  </td>`;
        } else {
          return `<td style="vertical-align: middle;padding: 0 20px;">
${row[c]
  .split(", ")
  .map((v) => _lang(nbText.BridgeGap.table.values[v.toLowerCase()]))
  .join(", ")}
          </td>`;
        }
      })
      .join("")}</tr>`;
  }

  table += `</tbody></table>`;

  let tableContainer = `<div style="max-height: 100%;">${table}</div>`;

  return html`${tableContainer}`;
};
```

## Icons

```{ojs}
country_flags = new Object({
  Cameroon: html`<svg width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#CC212D" d="M12 5v26h12V5H12zm7.882 15.59L18 19.223l-1.882 1.367l.719-2.212l-1.882-1.367h2.326L18 14.798l.719 2.212h2.326l-1.882 1.367l.719 2.213z"></path><path fill="#288541" d="M4 5a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h8V5H4z"></path><path fill="#FEE833" d="M32 5h-8v26h8a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4zM18.719 17.011L18 14.798l-.719 2.213h-2.326l1.882 1.367l-.719 2.212L18 19.223l1.882 1.367l-.719-2.212l1.882-1.367z"></path></g></svg>`,
  "Burkina Faso": html`<svg width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#009E49" d="M19.602 18.942l.99 3.048L18 20.106l-2.593 1.884l.99-3.048L15.101 18H0v9a4 4 0 0 0 4 4h28a4 4 0 0 0 4-4v-9H20.899l-1.297.942z"></path><path fill="#EF2B2D" d="M32 5H4a4 4 0 0 0-4 4v9h15.101l-1.296-.942h3.205L18 14.01l.99 3.048h3.205L20.899 18H36V9a4 4 0 0 0-4-4z"></path><path fill="#FCD116" d="M15.407 21.99L18 20.106l2.593 1.884l-.991-3.048L20.899 18l1.296-.942H18.99L18 14.01l-.99 3.048h-3.205l1.296.942l1.297.942z"></path></g></svg>`,
  Tanzania: html`<svg width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#1EB53A" d="M4 5a4 4 0 0 0-4 4v15.627L26.456 5H4z"></path><path fill="#00A3DD" d="M32 31a4 4 0 0 0 4-4V11.33L9.479 31H32z"></path><path fill="#141414" d="M32 5h-2.532L0 26.638V27a4 4 0 0 0 4 4h2.467L36 9.318V9a4 4 0 0 0-4-4z"></path><path fill="#FBD035" d="M26.456 5L0 24.627v2.011L29.468 5zM9.479 31L36 11.33V9.318L6.467 31z"></path></g></svg>`,
  Kenya: html`<svg width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#060" d="M36 27a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V9a4 4 0 0 1 4-4h28a4 4 0 0 1 4 4v18z"></path><path fill="#BB1600" d="M0 13h36v10H0z"></path><path fill="#141414" d="M32 5H4a4 4 0 0 0-4 4v4h36V9a4 4 0 0 0-4-4z"></path><path fill="#EEE" d="M0 13h36v1H0zm0 9h36v1H0z"></path><path fill="#141414" d="M23.054 9.404c-.066-.039-.186.089-.794.764c-.216.24-.486.539-.785.86c-.608.653-1.244 1.461-.783 1.935l-7.265 12.211c-.011.018-.019.047.003.087a.432.432 0 0 0 .294.177h.003c.046 0 .068-.021.079-.039l7.268-12.215c.626.148 1.024-.784 1.305-1.616c.14-.417.274-.796.381-1.1c.302-.856.356-1.027.294-1.064z"></path><path fill="#FFF" d="M22.305 10.208c-.216.24-.486.539-.786.861c-.886.952-1.124 1.528-.769 1.868l.018.016l-7.29 12.252c-.004.008.001.021.005.027a.378.378 0 0 0 .242.145h.002c.01 0 .023-.001.028-.01l7.279-12.234l.012-.02l.022.006c.458.13.846-.355 1.254-1.572c.14-.417.274-.796.381-1.101c.168-.475.314-.889.314-.984c-.082.046-.375.372-.712.746z"></path><path fill="#141414" d="M15.308 12.963c.461-.474-.174-1.282-.783-1.935c-.299-.322-.569-.62-.785-.86c-.608-.674-.728-.803-.794-.764c-.062.038-.008.208.293 1.063c.107.304.241.683.381 1.1c.28.833.678 1.764 1.305 1.616l7.268 12.215c.011.018.033.039.079.039h.003a.432.432 0 0 0 .294-.177c.021-.04.014-.069.003-.087l-7.264-12.21z"></path><path fill="#FFF" d="M15.25 12.937c.355-.34.118-.916-.769-1.868c-.3-.322-.569-.621-.786-.861c-.337-.374-.631-.7-.714-.745c0 .095.146.509.314.984c.107.305.242.684.381 1.101c.409 1.217.796 1.702 1.254 1.572l.022-.006l.012.02l7.279 12.234c.005.009.019.01.028.01h.002a.374.374 0 0 0 .242-.145c.004-.007.009-.02.005-.027l-7.29-12.252l.02-.017z"></path><path fill="#141414" d="M18.018 10.458L18 10.444l-.018.014c-2.492 1.87-3.704 4.331-3.704 7.523s1.211 5.653 3.704 7.524l.018.013l.018-.013c2.492-1.87 3.704-4.331 3.704-7.524s-1.212-5.655-3.704-7.523z"></path><path fill="#BB1600" d="M20.879 14.059c-.603-1.363-1.551-2.54-2.88-3.54c-1.326.999-2.273 2.174-2.877 3.533c.525 1.181.782 2.468.782 3.937c0 1.467-.256 2.751-.779 3.928c.604 1.356 1.55 2.529 2.873 3.527c1.326-.999 2.273-2.174 2.876-3.534c-.521-1.178-.776-2.461-.776-3.921c.002-1.462.258-2.747.781-3.93z"></path><path d="M18 18.927c.306 0 .555-.424.555-.946s-.249-.947-.555-.947c-.306 0-.554.424-.554.947c-.001.522.248.946.554.946zm-.231-2.497c-.502-.739-.746-1.677-.746-2.821c0-1.145.244-2.083.746-2.823v5.644zm.462 0c.501-.739.744-1.677.744-2.821c0-1.145-.243-2.083-.744-2.823v5.644zm-.462 3.1c-.502.738-.746 1.677-.746 2.821c0 1.146.244 2.082.746 2.822V19.53zm.462 0c.501.738.744 1.677.744 2.821c0 1.146-.243 2.082-.744 2.822V19.53z" fill="#FFF"></path></g></svg>`,
  Ethiopia: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path fill="#FCDD0A" d="M0 13h36v10H0z"> </path> <path fill="#088930" d="M32 5H4a4 4 0 0 0-4 4v4h36V9a4 4 0 0 0-4-4z"> </path> <path fill="#DA1219" d="M4 31h28a4 4 0 0 0 4-4v-4H0v4a4 4 0 0 0 4 4z"> </path> <circle fill="#0F47AF" cx="18" cy="18" r="9"> </circle> <g fill="#FCDD0A"> <path d="M13.25 24.469l1.719-5.531l-2.731-1.985h1.156l3.778 2.893l-.594.359l-.922-.83l-1.468 4.406z"> </path> <path d="M22.609 24.469l-4.73-3.345l-2.723 1.97l.357-1.1l3.964-2.824l.158.676l-1.128.759l3.739 2.759z"> </path> <path d="M25.382 15.64l-4.519 3.372l1.012 3.222l-.935-.677l-1.463-4.633l.693.058l.395 1.272l3.7-2.647z"> </path> <path d="M17.872 10.07l1.86 5.487l3.344.05l-.933.68l-4.549-.038l.271-.642l.979-.06l-1.327-4.37zm-7.669 5.477h5.906l1.063-3.254l.358 1.098L16.012 18l-.526-.456l.476-1.372l-4.783.029zm7.526 6.765h.417v3.647h-.417zm7.847-2.087l-.128.396L22 19.466l.128-.396z"> </path> <path d="M22.473 11.453l.337.245l-2.177 3.021l-.337-.244zm-9.359.245l.337-.245l2.174 3.021l-.336.245zm-2.637 8.923l-.129-.396l3.454-1.155l.129.397z"> </path> </g> </g></svg>`,
  Madagascar: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#FC3D32" d="M32 5H13v13h23V9a4 4 0 0 0-4-4z"></path><path fill="#007E3A" d="M13 31h19a4 4 0 0 0 4-4v-9H13v13z"></path><path fill="#EEE" d="M13 5H4a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h9V5z"></path></g></svg>`,
  Mauritania: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#CE2540" d="M32 5H4a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h28a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4z"></path><path fill="#0F6433" d="M0 9v18h36V9z"></path><path fill="#FFC514" d="M14.936 12.664l1.894 1.375l-.722 2.221l-.002.005l.007-.005L18 14.889l1.887 1.371l.006.005l-.001-.005l-.722-2.221l1.894-1.375h-2.341L18 10.437l-.723 2.227z"></path><path fill="#FFC514" d="M26.1 13.641c-.019 4.458-3.638 8.067-8.1 8.067s-8.081-3.609-8.1-8.067a8.373 8.373 0 0 0-.294 2.173a8.395 8.395 0 1 0 16.79 0a8.417 8.417 0 0 0-.296-2.173z"></path></g></svg>`,
  Niger: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#EEE" d="M0 13h36v10H0z"></path><path fill="#E05206" d="M32 5H4a4 4 0 0 0-4 4v4h36V9a4 4 0 0 0-4-4z"></path><circle fill="#E05206" cx="18" cy="18" r="4"></circle><path fill="#0DB02B" d="M32 31H4a4 4 0 0 1-4-4v-4h36v4a4 4 0 0 1-4 4z"></path></g></svg>`,
  Ghana: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#CC212D" d="M32 5H4a4 4 0 0 0-4 4v5h36V9a4 4 0 0 0-4-4z"></path><path fill="#FBD116" d="M15.423 22h5.185l-2.592-1.884zm3.587-4.941h3.215l-2.601 1.889l.991 3.052H36v-8H18.016zm-2.602 1.889l-2.601-1.889h3.215L18.016 14H0v8h15.416z"></path><path fill="#288541" d="M20.617 22.006L20.608 22h-5.186l-.009.006l.003-.006H0v5a4 4 0 0 0 4 4h28a4 4 0 0 0 4-4v-5H20.615l.002.006z"></path><path d="M13.807 17.059l2.601 1.889L15.416 22l-.002.006l.009-.006l2.593-1.884L20.608 22l.009.006l-.002-.006l-.991-3.052l2.601-1.889H19.01L18.016 14l-.994 3.059z" fill="#000000"></path></g></svg>`,
  Zimbabwe: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#EEE" d="M10.154 12L1.833 5.637a4.121 4.121 0 0 0-.5.381v.001A3.992 3.992 0 0 0 0 9v18a3.992 3.992 0 0 0 1.834 3.363L18 18l-7.846-6z"></path><path fill="#DE200F" d="M6.682 11.597l1.783 3.613l3.989.58l-2.887 2.813l.682 3.972l-3.567-1.876l-3.567 1.876l.681-3.972L.91 15.79l3.988-.58z"></path><path fill="#FFD200" d="M7.5 15.458c-.917-.75-1.292-1.292-1.958-2.333s-1.542-.917-1.917 0c-.583.125-.75.75-.75.75c.958-.292 1.583.333 1.667 1.667s-.25 1.708-.833 2.875s.083 1.458.083 1.458l.384 2.026h5.958l.825-3.568h.5c-.001 0-3.042-2.125-3.959-2.875z"></path><path fill="#FFAC33" d="M5.812 16.531l-.344.236s.625 1.369 1.531 1.566s3.837.523 3.837.523l.121-.523s-3.031-.365-3.792-.49s-1.353-1.312-1.353-1.312zm-.75 3.376s1.281-.106 1.938 0c.613.099 3.193.242 3.534.261l.113-.49c-.349-.056-3.075-.491-3.835-.536c-.812-.048-1.624.346-1.75.765zm.657.968l.156 1.026h4.258l.182-.785c-2.073-.41-4.596-.241-4.596-.241z"></path><path fill="#F15A29" d="M10.173 21.951H4.134l-.008-.04l-.379-2.003a.64.64 0 0 1-.278-.345c-.109-.3-.043-.693.194-1.169c.088-.176.171-.334.247-.481c.42-.806.651-1.25.582-2.369c-.047-.746-.264-1.273-.627-1.525c-.263-.182-.591-.214-.975-.097l-.086.026l.023-.087c.007-.026.176-.638.762-.78c.186-.438.494-.707.847-.739c.407-.035.814.231 1.148.755c.643 1.004 1.021 1.564 1.948 2.322c.905.74 3.925 2.852 3.956 2.873l.13.091h-.619l-.826 3.568zm-5.956-.099h5.876l.825-3.568h.382c-.591-.415-3.032-2.132-3.832-2.787c-.938-.768-1.32-1.332-1.968-2.345c-.313-.491-.694-.744-1.055-.709c-.322.029-.604.285-.774.701l-.01.024l-.026.005c-.418.09-.612.458-.681.627c.376-.094.701-.048.968.137c.39.27.622.824.67 1.601c.072 1.147-.164 1.6-.592 2.422a37.48 37.48 0 0 0-.246.479c-.221.442-.287.817-.191 1.087c.081.225.243.3.25.303l.024.011l.005.025l.375 1.987z"></path><path fill="#319209" d="M35.873 8A4 4 0 0 0 32 5H4c-.798 0-1.542.234-2.166.636l-.001.001L4.923 8h30.95zm0 20A4.001 4.001 0 0 1 32 31H4a3.988 3.988 0 0 1-2.166-.636l-.001-.001L4.923 28h30.95z"></path><path fill="#FFD200" d="M4.923 8L18 18L4.923 28h30.95c.083-.321.127-.653.127-1V9c0-.343-.046-.682-.127-1c0-.002-30.95 0-30.95 0z"></path><path fill="#DE200F" d="M10.154 12l5.231 4H36v-4zm0 12H36v-4H15.385z"></path><path fill="#141414" d="M15.385 16L1.833 5.637a4.121 4.121 0 0 0-.5.381v.001L17 18L1.333 29.981c.156.14.324.267.501.382L15.385 20H36v-4H15.385z"></path></g></svg>`,
  "Sub-Saharan Africa": html`<svg width="40px" height="40px" version="1.1" id="_x32_" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve" fill="#32821c" stroke="#32821c"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <style type="text/css"> .st0{fill:#32821c;} </style> <g> <path class="st0" d="M495.001,189.882c-0.938-1.114-2.43-1.587-3.833-1.228l-37.986,9.826c-1.562,0.403-3.194-0.228-4.088-1.562 l-16.51-24.756c-0.193-0.29-0.421-0.554-0.693-0.773l-15.58-13.247c-0.422-0.359-0.755-0.807-0.992-1.316l-19.458-42.969 c-0.088-0.219-0.202-0.42-0.342-0.605L384.122,96.97c-0.027-0.044-0.053-0.079-0.079-0.114l-15.756-24.424 c-0.526-0.825-0.729-1.825-0.526-2.79l0.464-2.317c0.22-1.105,0.922-2.053,1.912-2.587c1.001-0.535,2.176-0.596,3.22-0.167l2.413,1 c1.351,0.562,2.912,0.281,3.991-0.719c1.071-0.992,1.474-2.518,1.036-3.913l-2.711-8.51c-0.403-1.28-1.456-2.246-2.772-2.535 l-26.932-5.992c-0.57-0.122-1.176-0.114-1.737,0.027l-21.44,5.359c-0.632,0.158-1.298,0.149-1.931-0.035l-18.756-5.246 c-0.693-0.192-1.324-0.578-1.798-1.123l-4.861-5.474c-0.676-0.755-1.622-1.211-2.631-1.255l-11.641-0.587 c-1.931-0.088-3.632,1.289-3.913,3.21l-1.403,9.37c-0.158,1.018-0.711,1.93-1.544,2.518c-0.843,0.588-1.886,0.816-2.886,0.632 l-24.73-4.676c-1.351-0.263-2.448-1.22-2.877-2.518l-1.798-5.396c-0.5-1.491-1.878-2.518-3.448-2.57l-19.677-0.676 c-1.15-0.035-2.211-0.596-2.895-1.509l-6.378-8.51c-0.641-0.851-0.886-1.939-0.684-2.982c0.201-1.053,0.842-1.957,1.754-2.509 l1.675-1.009c1.72-1.027,2.325-3.22,1.403-4.992L209.93,2.004c-0.747-1.404-2.29-2.194-3.869-1.966L132.685,10.4 c-0.307,0.035-0.606,0.123-0.895,0.237l-21.432,8.729c-0.386,0.166-0.799,0.254-1.22,0.272L95.4,20.357 c-0.921,0.053-1.78,0.43-2.43,1.071L67.441,46.176c-0.578,0.562-0.965,1.289-1.096,2.079l-2.018,12.08 c-0.166,1.062-0.789,1.992-1.692,2.571l-22.696,14.37c-0.536,0.333-0.983,0.807-1.281,1.359l-20.625,37.294 c-0.342,0.614-0.508,1.298-0.474,2l1.596,34.231c0.009,0.298-0.009,0.588-0.07,0.878l-2.903,15.256 c-0.211,1.114,0.096,2.272,0.824,3.15l55.522,65.831c0.922,1.088,2.378,1.561,3.773,1.237l24.59-5.974 c0.377-0.088,0.763-0.123,1.158-0.097l34.433,2.404c0.474,0.044,0.956-0.026,1.421-0.166l25.608-8.291 c1.219-0.394,2.552-0.14,3.544,0.666l15.519,12.704c0.754,0.605,1.728,0.912,2.702,0.834l14.344-1.202 c1.053-0.079,2.088,0.271,2.859,0.991c0.782,0.71,1.229,1.71,1.229,2.772v13.905c0,0.192-0.018,0.377-0.044,0.562l-2.211,14.712 c-0.149,1.035,0.131,2.105,0.799,2.921l15.905,19.686c0.334,0.42,0.579,0.912,0.719,1.43l12.818,49.69 c0.184,0.692,0.158,1.421-0.061,2.096l-11.694,36.661c-0.28,0.878-0.228,1.834,0.14,2.676l19.976,44.733 c0.149,0.333,0.254,0.684,0.298,1.062l3.938,30.774c0.088,0.711,0.395,1.378,0.843,1.931l19.212,23.046 c0.562,0.685,0.868,1.526,0.868,2.413v16.791c0,1.079,0.465,2.114,1.29,2.833c0.807,0.72,1.894,1.036,2.974,0.895l33.977-4.421 l28.529-3.966c0.895-0.131,1.72-0.57,2.316-1.263l43.312-49.716c0.42-0.49,0.719-1.096,0.842-1.736l2.001-9.957 c0.193-0.974,0.772-1.842,1.605-2.395l4.553-3.026c1.018-0.694,1.649-1.825,1.675-3.053l0.747-30.775 c0.026-0.868,0.35-1.71,0.921-2.368l9.202-10.616c0.474-0.544,1.079-0.93,1.772-1.14l18.686-5.545 c1.606-0.473,2.702-1.938,2.702-3.615v-37.442c0-0.316-0.035-0.624-0.114-0.922l-9.106-35.67c-0.439-1.72,0.377-3.509,1.965-4.308 l3.088-1.543c0.562-0.281,1.035-0.685,1.386-1.185l27.125-38.293c0.386-0.552,0.921-0.982,1.526-1.263l21.871-9.799 c0.834-0.377,1.509-1.053,1.886-1.886l23.599-52.207C496.142,192.532,495.94,190.988,495.001,189.882z"></path> <path class="st0" d="M485.606,356.242c-0.588-1.114-1.684-1.868-2.93-2c-1.246-0.14-2.483,0.351-3.29,1.316l-18.265,21.634 c-0.369,0.447-0.834,0.799-1.369,1.027l-10.237,4.483c-1.377,0.596-2.255,1.956-2.255,3.457v21.168 c0,0.316-0.044,0.622-0.123,0.921l-2.948,11.8c-0.167,0.684-0.14,1.395,0.07,2.07l6.799,21.072c0.316,0.974,1.001,1.764,1.912,2.22 c0.904,0.448,1.966,0.518,2.914,0.184l13.632-4.747c1.158-0.404,2.045-1.333,2.395-2.5l16.072-55.488l3.728-12.677 c0.272-0.93,0.176-1.939-0.271-2.808L485.606,356.242z"></path> </g> </g></svg>`,
  Malawi: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#77B255" d="M36 27a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V9a4 4 0 0 1 4-4h28a4 4 0 0 1 4 4v18z"></path><path fill="#DD2E44" d="M0 13h36v10H0z"></path><path fill="#141414" d="M32 5H4a4 4 0 0 0-4 4v4h36V9a4 4 0 0 0-4-4z"></path><path d="M23.191 12a5.992 5.992 0 0 0-10.382 0h10.382zm-5.493-6h.603L18 8.163zm-1.514.18l.594-.102l.068 2.183zm-1.463.433l.569-.201l.435 2.14zm-1.368.673l.527-.293l.79 2.036zm-1.235.895l.47-.378l1.122 1.873zm-1.067 1.09l.401-.452l1.421 1.658zm-.866 1.255l.317-.513l1.681 1.393zM10.898 12l-1.13-.65l-.226.559l.364.091zm15.355 0l.218-.054l-.221-.557l-1.074.611zm-.731-1.951l.312.512l-2.001.872zm-.943-1.198l.394.451l-1.826 1.198zm-1.132-1.023l.464.38l-1.596 1.487zm-1.288-.816l.521.296l-1.323 1.735zm-1.408-.588l.564.204l-1.011 1.934zm-1.487-.341l.59.106l-.67 2.077z" fill="#DD2E44"></path></g></svg>`,
  Zambia: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#1A8A00" d="M32 5H4a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h28a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4z"></path><path fill="#EF7D00" d="M31 31h1a4 4 0 0 0 4-4V15h-5v16z"></path><path fill="#141414" d="M26 15h5v16h-5z"></path><path fill="#DE200F" d="M21 15h5v16h-5z"></path><path fill="#EF7D00" d="M35.083 8.256c-.109-.021-.716.325-.716.325s.564-.65.434-.65c-.13 0-.866.346-.866.346s.455-.563.303-.498c-.152.065-.976.433-1.604.696c.088-.149.065-.372 0-.372c-.064 0-.434.238-.997.369c-.564.13-1.408.607-1.777.542c-.368-.065-1.105 0-1.105 0s-.216-.325-.043-.412c.172-.087.304.13.304.13s.304-.13.304-.314s-.521-.206-.521-.206s-.218-.281-.563-.281c-.91 0-.976.975-.976.975s-.369-.13-.715-.217c-.347-.087-.954-.043-1.56-.412c-.606-.369-.997-.498-.261.282c-1.084-.369-1.646-1.105-1.799-.786c-.152.32.412.699.412.699s-.304-.086-.563-.325c-.26-.239-.629-.39-.281.13c-.455-.13-.13.347-.13.347s-.369.108 0 .368c.368.26 1.04.369 1.04.369s-.304.216-.109.303s.521.022.521.022s-.26.216 0 .303s.585 0 .585 0s-.108.217.151.314c.261.098.673-.119.673-.119s-.195.13 0 .238c.195.108.498-.119.498-.119s-.173.292 0 .336c.173.043.455-.173.455-.173s-.173.281 0 .303c.173.022.563-.195.563-.195s-.238.303 0 .303c.239 0 .521-.151.521-.151s-.065.238.13.325c.195.087.476-.152.476-.152s.066.456.022.715c-.043.26.281.065.281.065s-.044.39-.304.369c-.26-.022-.521.325-.433.412c.087.087.433-.065.433-.065s-.021.477.108.437c.13-.04.347-.307.347-.307s.13.347.218.304c.087-.044.13-.238.13-.347s.237-.152.237-.152s.065.433.152.349c.088-.085.108-.371.238-.457c.13-.086.087.498.217.455c.131-.043.065-.434.022-.564c-.043-.13.261.108.239 0c-.021-.109-.261-.325-.261-.325s.303.109.217 0s-.13-.39 0-.329s.239-.191.239-.191s.346.26.562.173c.216-.086-.281-.39-.281-.39s.759.26.926.217c.168-.044-.255-.325-.255-.325s.477.108.564 0c.086-.109-.31-.195-.31-.195s.525.087.591 0c.065-.087-.151-.195-.151-.195s.866-.021 1.04-.325c.867.022 1.82-.671 1.907-.823c.086-.152-.151-.152-.151-.152s.521-.412.455-.477c-.065-.065-.347.086-.347.086s.672-.585.564-.606zm-6.436 3.727c-.28 0-.088-.151-.132-.303c-.044-.152.152-.021.13-.152c-.023-.13 0-.758 0-.758c.217.217.325.499.304.715c-.021.217.108.238.151.347c.044.109-.172.151-.453.151z"></path></g></svg>`,
  Mali: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#14B53A" d="M4 5a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h8V5H4z"></path><path fill="#FCD116" d="M12 5h12v26H12z"></path><path fill="#CE1126" d="M32 5h-8v26h8a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4z"></path></g></svg>`,
  Benin: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#FCD116" d="M32 5H14v13h22V9a4 4 0 0 0-4-4z"></path><path fill="#E8112D" d="M14 31h18a4 4 0 0 0 4-4v-9H14v13z"></path><path fill="#008751" d="M14 5H4a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h10V5z"></path></g></svg>`,
  Uganda: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#D90001" d="M36 27v-1H0v1a4 4 0 0 0 4 4h28a4 4 0 0 0 4-4z"></path><path fill="#FCDC02" d="M0 22h36v4H0z"></path><path fill="#141414" d="M0 18h36v4H0z"></path><path fill="#D90001" d="M0 14h36v4H0z"></path><path fill="#FCDC02" d="M0 10h36v4H0z"></path><path fill="#141414" d="M0 9v1h36V9a4 4 0 0 0-4-4H4a4 4 0 0 0-4 4z"></path><circle fill="#FFF" cx="18" cy="18" r="4"></circle><path fill="#D90000" d="M17.344 15.031l-.267-.703s.579-.203 1.142 0c.429.155.469.703.469.703l-.671.203l-.673-.203z"></path><path fill="#FCDC02" d="M17.594 14.922v-.684s.111-.043.423 0s.453.262.453.262l-.438.532l-.438-.11z"></path><path fill="#141414" d="M17.745 16.896c-.083-.146 0-1 .239-1.062c.239-.062.698-.812 0-1.062s-.844.479-.844.479s-.69.203-.604.375c.083.167.667-.062.792.083s-.062.354-.562.938s-.167 1.375.062 1.579s.5.359.708.546s.448.292.448.292v.604s-.698.062-1.031.021s-.562.188-.646.458s.125.417.125.209s.083-.084.102.083c.019.167.168.104.168-.104s.083-.125.104-.021s.167-.042.188-.167s.208-.188.375-.229s.614.041.614.041v1.104s-.927.062-1.01.188s.562.104.562.104s-.188.354-.104.375s.667-.354.896-.396s.583.104.625 0s-.562-.25-.625-.354s-.188-1.062-.188-1.062s.271-.022.605-.001c.333.021.25-.271.042-.562s-.021-.375.333-.312c.354.063.625 0 .625-.563s-1.916-1.438-1.999-1.584zm.729 2.708h-.229l.083-.417c0 .001.292.417.146.417z"></path><path fill="#D90000" d="M17.474 15.812c.029-.249-.375-.229-.396 0s.355.355.396 0z"></path><path fill="#9CA69C" d="M17.75 17.047c.115-.041 1.406.547 1.75.703c.344.156.303.75.245 1.109s-.261.469-.261.469s-.225-.58-.938-.859c-.957-.375-1.234-1.266-.796-1.422z"></path><path fill="#D90000" d="M19.203 17.734c.421.11 1.312.312 1.391 1.219c.078.906-.849 1.438-.849 1.438l.155-.281l-.275.094l.12-.204l-.433.094s.725-.578.472-1.094c.019.43-.269.547-.269.547s.248-.596-.828-1.25l.281-.072l-.28-.225l.594.225l-.282-.35l.562.219l-.359-.36z"></path><path fill="#9CA69C" d="M17.594 15.336a.102.102 0 1 1-.204 0a.102.102 0 1 1 .204 0z"></path></g></svg>`,
  Chad: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#002664" d="M4 5a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h8V5H4z"></path><path fill="#FECB00" d="M12 5h12v26H12z"></path><path fill="#C60C30" d="M32 5h-8v26h8a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4z"></path></g></svg>`,
  Senegal: html`<svg  width="40px" height="40px" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--twemoji" preserveAspectRatio="xMidYMid meet" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="#00853F" d="M4 5a4 4 0 0 0-4 4v18a4 4 0 0 0 4 4h8V5H4z"></path><path fill="#FDEF42" d="M12 5h12v26H12z"></path><path fill="#E31B23" d="M32 5h-8v26h8a4 4 0 0 0 4-4V9a4 4 0 0 0-4-4z"></path><path fill="#00853F" d="M18.869 16.674L18 14l-.869 2.674H14.32l2.274 1.652L15.726 21L18 19.348L20.274 21l-.868-2.674l2.274-1.652z"></path></g></svg>`,
});

hs_icons = new Object({
  human: html`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" style="height: 30px;fill: grey;"><path d="M160 0a48 48 0 1 1 0 96 48 48 0 1 1 0-96zM88 384H70.3c-10.9 0-18.6-10.7-15.2-21.1L93.3 248.1 59.4 304.5c-9.1 15.1-28.8 20-43.9 10.9s-20-28.8-10.9-43.9l53.6-89.2c20.3-33.7 56.7-54.3 96-54.3h11.6c39.3 0 75.7 20.6 96 54.3l53.6 89.2c9.1 15.1 4.2 34.8-10.9 43.9s-34.8 4.2-43.9-10.9l-33.9-56.3L265 362.9c3.5 10.4-4.3 21.1-15.2 21.1H232v96c0 17.7-14.3 32-32 32s-32-14.3-32-32V384H152v96c0 17.7-14.3 32-32 32s-32-14.3-32-32V384z"/></svg>`,
  crop: html`<svg height="30px" fill="grey" viewBox="0 0 14 14" role="img" focusable="false" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="m 9.2809236,1.0031187 c -0.021203,1.53e-4 -0.042468,0.0042 -0.061193,0.0153 -0.037695,0.02227 -0.061682,0.06327 -0.061193,0.107087 4.895e-4,0.04895 0.014503,1.205006 0.3442088,1.774588 0.1970404,0.343658 0.4168445,0.512488 0.6731196,0.512488 0.117,0 0.240915,-0.03219 0.374805,-0.107087 0.159346,-0.08934 0.332092,-0.210197 0.390103,-0.4207 0.05042,-0.183578 0.0013,-0.395366 -0.145333,-0.650172 -0.329461,-0.57056 -1.4075533,-1.190259 -1.4533254,-1.216204 -0.018847,-0.01077 -0.039989,-0.01545 -0.061193,-0.0153 z m 2.9525474,0.902592 c -0.02099,0.002 -0.04333,0.01022 -0.06119,0.02295 -0.04014,0.02839 -0.979389,0.697902 -1.262099,1.292695 -0.247953,0.521607 -0.163079,0.877626 0.267718,1.08617 0.110147,0.05263 0.245933,0.107087 0.390103,0.107087 0.259947,0 0.467941,-0.17085 0.634874,-0.520137 0.281976,-0.594793 0.165526,-1.829539 0.160631,-1.881675 -0.0042,-0.04357 -0.02919,-0.08108 -0.06884,-0.09944 -0.02007,-0.0091 -0.0402,-0.0096 -0.06119,-0.0077 z m -2.5165495,1.545116 c -0.6430127,0 -1.4131226,0.205607 -1.4456771,0.214174 -0.042835,0.01126 -0.07337,0.04155 -0.08414,0.08414 -0.011015,0.04283 -0.00147,0.09179 0.030596,0.122385 0.035737,0.03451 0.886376,0.842318 1.5374661,1.017329 0.1436804,0.03867 0.2762855,0.06119 0.3901035,0.06119 0.3417,0 0.553488,-0.168096 0.650172,-0.512488 0.04798,-0.173053 0.085,-0.376825 -0.02295,-0.566033 -0.09619,-0.168647 -0.288584,-0.28834 -0.58133,-0.367156 -0.129239,-0.03476 -0.2872391,-0.05354 -0.4742439,-0.05354 z m 3.1820195,0.74961 c -0.02081,-0.0035 -0.04828,6.1e-5 -0.06884,0.0076 -0.04602,0.01713 -1.126374,0.423515 -1.552764,0.925539 -0.374499,0.440832 -0.384963,0.805663 -0.02295,1.116767 0.127525,0.109412 0.282404,0.221823 0.481892,0.221823 0.204384,0 0.407054,-0.111738 0.611927,-0.351858 0.426635,-0.50178 0.64136,-1.722941 0.650172,-1.774587 0.0076,-0.04308 -0.01212,-0.08683 -0.04589,-0.114737 -0.01713,-0.01395 -0.03274,-0.02705 -0.05354,-0.0306 z m -4.2911369,0.734312 c -0.03745,0.0059 -0.085303,0.02252 -0.1070872,0.06119 -0.021785,0.03867 -0.015604,0.09234 0.00765,0.130034 0.025946,0.04259 0.6465007,1.046456 1.2315027,1.384485 0.2173564,0.125812 0.3990984,0.183578 0.5660324,0.183578 0.341945,0 0.506002,-0.263985 0.558383,-0.351858 0.09154,-0.15445 0.177214,-0.340476 0.122386,-0.550734 -0.04895,-0.187984 -0.202242,-0.351369 -0.466595,-0.50484 C 9.93336,4.9483337 8.6616537,4.9349937 8.6078041,4.9347487 Z M 8.416577,5.9597267 c -0.021142,0.0031 -0.043936,0.009 -0.061193,0.02295 -0.034757,0.0279 -0.053238,0.07092 -0.045894,0.114736 0.00832,0.0492 0.2096461,1.213329 0.627225,1.743992 0.2264129,0.28736 0.4506841,0.428348 0.6807686,0.428348 0.1429461,0 0.2817311,-0.0552 0.4283484,-0.16828 0.142701,-0.110146 0.294337,-0.250951 0.321262,-0.466594 0.02399,-0.192879 -0.05581,-0.402892 -0.244771,-0.642523 -0.4188025,-0.529194 -1.5948647,-1.004906 -1.6445531,-1.024977 -0.020561,-0.0083 -0.040051,-0.01077 -0.061193,-0.0076 z m 4.245242,0.757259 c -0.0492,4.9e-4 -1.210452,0.01671 -1.782237,0.344209 -0.503248,0.28785 -0.632732,0.632304 -0.397752,1.047925 0.06854,0.120916 0.23394,0.397752 0.573681,0.397752 0.149311,0 0.314408,-0.05195 0.50484,-0.160631 0.573008,-0.328237 1.190259,-1.399905 1.216205,-1.445677 0.02203,-0.03794 0.01462,-0.08469 -0.0076,-0.122385 -0.02227,-0.03769 -0.05544,-0.0607 -0.107087,-0.06119 z m -4.696538,0.397752 c -0.021326,-0.0018 -0.041244,0.0058 -0.061193,0.0153 -0.039898,0.01909 -0.065905,0.05538 -0.068842,0.09944 -0.00343,0.04993 -0.079122,1.231992 0.2065253,1.843429 0.182599,0.393347 0.41507,0.581331 0.6960668,0.581331 0.1013351,0 0.2018134,-0.02264 0.3212616,-0.07649 0.1649754,-0.0749 0.3453103,-0.178071 0.4206996,-0.382454 0.067312,-0.182599 0.036716,-0.405647 -0.091789,-0.680769 -0.283934,-0.611437 -1.317968,-1.345994 -1.3615371,-1.376835 -0.018113,-0.01273 -0.039867,-0.02117 -0.061193,-0.02295 z m 1.5145188,2.080552 c -0.060238,0.122931 -0.075818,0.275244 -0.045894,0.451296 0.032065,0.184312 0.1067201,0.6195763 0.6731192,0.6195763 0.07735,0 0.167301,-0.0142 0.260069,-0.0306 0.648397,-0.116266 1.596762,-0.9144633 1.636904,-0.9484863 0.03329,-0.02839 0.04632,-0.07931 0.03824,-0.122386 -0.0081,-0.04332 -0.04253,-0.07759 -0.08414,-0.09179 -0.03525,-0.01224 -0.869548,-0.298314 -1.514518,-0.298314 -0.102559,0 -0.200284,0.0083 -0.283017,0.02295 -0.3562935,0.06364 -0.580371,0.192867 -0.6807677,0.397753 z M 7.1162325,8.0020317 c -0.043569,0.0081 -0.077837,0.03464 -0.091789,0.07649 -0.01591,0.04724 -0.3916332,1.171718 -0.2753671,1.835781 0.088607,0.5069203 0.3259734,0.7649083 0.6960668,0.7649083 0.053605,0 0.1058021,-0.0062 0.1606308,-0.0153 0.1781931,-0.03035 0.3792722,-0.09001 0.5048396,-0.267718 C 8.222229,10.237826 8.2473792,10.021939 8.1947536,9.7230737 8.0775084,9.0582757 7.2731306,8.0813957 7.238618,8.0402747 7.20998,8.0064947 7.160536,7.9937047 7.1162326,8.0020247 Z m -1.2315027,0.871996 c -0.044059,0.0037 -0.080836,0.0287 -0.099438,0.06884 -0.020561,0.04577 -0.5052068,1.1246603 -0.4589451,1.7975353 0.041122,0.561993 0.2702269,0.83375 0.7037158,0.83375 0.022274,0 0.045344,0.0012 0.068842,0 0.020075,-0.0013 0.040652,-0.0056 0.061193,-0.0076 -0.9887011,0.408039 -2.8534922,1.023508 -5.063695,0.940791 -0.30596346,0.340476 0.2141743,0.489541 0.2141743,0.489541 0,0 3.0660728,-0.0025 5.0407472,-1.323292 -0.021196,0.03988 -0.036343,0.08302 -0.053544,0.130035 -0.061438,0.168402 -0.1154706,0.369481 -0.022947,0.566032 0.082977,0.176235 0.2616599,0.310736 0.5507342,0.413051 0.1872496,0.06609 0.4449932,0.09944 0.7649085,0.09944 0.5717844,0 1.153482,-0.102926 1.1779591,-0.107087 0.043569,-0.0081 0.077348,-0.04204 0.091789,-0.08414 0.014442,-0.0421 0.00667,-0.08934 -0.022947,-0.122386 -0.033534,-0.03721 -0.8309966,-0.914524 -1.4686244,-1.139713 -0.2380253,-0.08408 -0.4339572,-0.106885 -0.5966286,-0.07649 0.050741,-0.04332 0.10459,-0.08439 0.1529817,-0.130035 0,0 -0.1256658,0.06461 -0.3136125,0.152982 0.00524,-0.0055 0.01021,-0.0095 0.015298,-0.0153 C 6.7542165,11.213609 6.8091063,10.996803 6.7873217,10.694511 6.7400807,10.022126 6.029328,8.9721207 5.999466,8.9275727 5.974744,8.8911027 5.928788,8.8713327 5.8847297,8.8740327 Z m 2.6389344,1.3538883 c -0.341593,0.03694 -0.5311525,0.234123 -0.5889796,0.58898 -0.02717,0.177948 -0.03696,0.383617 0.091789,0.558383 0.1155317,0.156408 0.3175288,0.253521 0.6195759,0.298314 0.065599,0.0098 0.1323597,0.0153 0.2065253,0.0153 0.6787492,0 1.6493262,-0.381597 1.6904482,-0.397752 0.04137,-0.01616 0.07062,-0.04798 0.07649,-0.09179 0.0059,-0.04381 -0.0104,-0.08806 -0.04589,-0.114736 -0.0399,-0.02986 -0.9906484,-0.741778 -1.6598516,-0.8414 -0.1474131,-0.02221 -0.2762392,-0.02761 -0.3901033,-0.0153 z"></path></g></svg>`,
  livestock: html`<svg height="40px" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" fill="grey"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path fill="grey" d="M468.958 108.958c-27.507 2.08-48.997 7.94-71.375 22.572-5.333-2.214-12.62-17.738-16-16-11.82 6.08-14.892 19.555-4.916 32.817l-59.084 9.916c-24.776 3.341-49.567 4.838-74.187 5.334 1.326 3.832 2.96 7.636 4.812 10.05 5.219 6.802 20.323 6.21 21.07 14.75 1.935 22.098-24.876 47.415-47.056 47.057-15.401-.248-17.017-28.762-31.604-33.713-19.097-6.482-41.62 18.77-59.699 9.832-15.267-7.547-24.992-39.8-27.836-50.41-10.213-.127-20.327-.142-30.316.035-12.564.366-22.902 5.645-29.408 14.239-8.676 11.458-11.652 26.658-13.254 42.925-1.78 18.057 6.147 53.007 5.517 70.282-.504 13.85-7.493 11.87-11.912 18.888-13.52 21.47 8.894 20.83 17.014 5.56 12.482-23.473 4.253-63.11 7.195-92.974 1.855-35.76 10.597-23.937 15.664-24.588-4.2 13.065-6.21 30.962-7 51.334 6.895-2.342 36.498-11.6 42.73-.174 6.872 12.598-27.802 22.016-23.878 35.819 2.464 8.666 22.95 2.378 24.582 11.238 3.322 18.035-32.13 38.713-42.236 44.209.812 23.329 1.564 45.567 1.238 65.086H88.91c-4.234-16.543-12.038-49.944-4.06-55.084 21.425-18.091 29.836-37.484 42.732-56.428 8.755 2.556 16.92 4.787 24.782 6.672 3.553.972 7.244 1.771 10.984 2.44 24.859 4.967 61.553 5.678 90.783-.172 3.76 34.12 7.263 68.452 4.602 102.572h28.957c-12.375-26.902-4.263-65.044 13.892-86.27l44.934-33.462c24.881-16.384 42.93-37.996 55.982-63.38 30.402 3.413 57.086 3.29 77.192-.786l12.84-19.55c-24.257-17.857-43.3-36.585-62.948-58.13 10.063-14.533 25.027-22.765 39.375-32.506zm-39.375 54.572a8 8 0 1 1 0 16 8 8 0 0 1 0-16zM366.2 183.481c5.029 9.822-26.17 10.808-24.933 21.772.998 8.847 22.204 3.839 23.53 12.643 3.818 25.373-28.44 53.805-54.08 54.78-14.262.544-34.902-14.06-32.308-28.093 2.605-14.092 34.551-1.657 40.383-14.748 4.724-10.603-18.352-22.01-12.992-32.307 6.264-12.032 30.364-22.553 41.934-22.646 11.57-.093 15.606 3.347 18.466 8.6zm-26.585 126.346l-34.707 23.96 6.464 69.255h34.414c-11.783-22.454-15.58-55.506-6.171-93.215zm-204.561 1.41c-6.047 12.184-14.147 21.97-22.174 31.242 5.97 3.235 11.648 5.414 17.154 6.614 11.218 2.443 21.636.333 29.948-4.408 10.056-5.737 17.521-14.452 24.115-23.368-14.615-.869-32.96-2.962-49.043-10.08zm24.252 52c-8.737 2.585-17.452 3.7-25.566 2.96 5.167 12.624 10.45 24.152 15.824 36.845h28.306c-10.393-18.48-16.148-29.285-18.564-39.805z"></path></g></svg>`,
});

climate_risk_icons = new Object({
  "Extreme Weather Events": html`<svg width="35px" height="35px" viewBox="0 0 60 60" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <title>crazy-weather</title> <desc>Created with Sketch.</desc> <defs> </defs> <g id="People" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="Icon-31" fill="#000000"> <path d="M25.8945,48.5527 C25.6475,48.0597 25.0465,47.8597 24.5525,48.1057 C24.0585,48.3527 23.8585,48.9527 24.1055,49.4477 L25.1055,51.4477 C25.2805,51.7977 25.6335,51.9997 26.0005,51.9997 C26.1505,51.9997 26.3035,51.9657 26.4475,51.8947 C26.9415,51.6477 27.1415,51.0467 26.8945,50.5527 L25.8945,48.5527 Z M25.8945,54.5527 C25.6475,54.0597 25.0465,53.8597 24.5525,54.1057 C24.0585,54.3527 23.8585,54.9527 24.1055,55.4477 L25.1055,57.4477 C25.2805,57.7977 25.6335,57.9997 26.0005,57.9997 C26.1505,57.9997 26.3035,57.9657 26.4475,57.8947 C26.9415,57.6477 27.1415,57.0467 26.8945,56.5527 L25.8945,54.5527 Z M19.8945,44.5527 C19.6475,44.0587 19.0475,43.8597 18.5525,44.1057 C18.0585,44.3527 17.8585,44.9527 18.1055,45.4477 L19.1055,47.4477 C19.2805,47.7977 19.6335,47.9997 20.0005,47.9997 C20.1505,47.9997 20.3035,47.9657 20.4475,47.8947 C20.9415,47.6477 21.1415,47.0467 20.8945,46.5527 L19.8945,44.5527 Z M19.8945,50.5527 C19.6475,50.0587 19.0475,49.8597 18.5525,50.1057 C18.0585,50.3527 17.8585,50.9527 18.1055,51.4477 L19.1055,53.4477 C19.2805,53.7977 19.6335,53.9997 20.0005,53.9997 C20.1505,53.9997 20.3035,53.9657 20.4475,53.8947 C20.9415,53.6477 21.1415,53.0467 20.8945,52.5527 L19.8945,50.5527 Z M31.8945,56.5527 C31.6475,56.0597 31.0485,55.8607 30.5525,56.1057 C30.0585,56.3527 29.8585,56.9527 30.1055,57.4477 L31.1055,59.4477 C31.2805,59.7977 31.6335,59.9997 32.0005,59.9997 C32.1505,59.9997 32.3035,59.9657 32.4475,59.8947 C32.9415,59.6477 33.1415,59.0467 32.8945,58.5527 L31.8945,56.5527 Z M19.8945,56.5527 C19.6475,56.0597 19.0475,55.8607 18.5525,56.1057 C18.0585,56.3527 17.8585,56.9527 18.1055,57.4477 L19.1055,59.4477 C19.2805,59.7977 19.6335,59.9997 20.0005,59.9997 C20.1505,59.9997 20.3035,59.9657 20.4475,59.8947 C20.9415,59.6477 21.1415,59.0467 20.8945,58.5527 L19.8945,56.5527 Z M3.8355,13.8007 L5.6835,14.5667 C5.8085,14.6177 5.9385,14.6427 6.0655,14.6427 C6.4585,14.6427 6.8305,14.4097 6.9905,14.0257 C7.2015,13.5157 6.9595,12.9297 6.4495,12.7187 L4.6015,11.9527 C4.0905,11.7407 3.5065,11.9847 3.2945,12.4937 C3.0835,13.0037 3.3255,13.5897 3.8355,13.8007 L3.8355,13.8007 Z M23.9745,6.9897 C24.0995,7.0407 24.2295,7.0657 24.3565,7.0657 C24.7495,7.0657 25.1215,6.8327 25.2815,6.4487 L26.0465,4.6007 C26.2585,4.0907 26.0165,3.5057 25.5055,3.2937 C24.9955,3.0817 24.4115,3.3247 24.1995,3.8347 L23.4335,5.6827 C23.2225,6.1927 23.4645,6.7777 23.9745,6.9897 L23.9745,6.9897 Z M12.7185,6.4487 C12.8785,6.8337 13.2505,7.0667 13.6435,7.0667 C13.7705,7.0667 13.8995,7.0417 14.0255,6.9897 C14.5355,6.7797 14.7775,6.1947 14.5665,5.6837 L13.8005,3.8347 C13.5885,3.3247 13.0045,3.0817 12.4945,3.2937 C11.9835,3.5047 11.7415,4.0897 11.9535,4.6007 L12.7185,6.4487 Z M0.9995,20.0007 L4.9995,19.9997 C5.5525,19.9997 5.9995,19.5517 5.9995,18.9997 C5.9995,18.4477 5.5525,17.9997 4.9995,17.9997 L0.9995,18.0007 C0.4475,18.0007 -0.0005,18.4487 -0.0005,19.0007 C-0.0005,19.5537 0.4475,20.0007 0.9995,20.0007 L0.9995,20.0007 Z M8.3935,9.8087 C8.5885,10.0037 8.8445,10.1017 9.1005,10.1017 C9.3565,10.1017 9.6125,10.0037 9.8075,9.8087 C10.1985,9.4177 10.1985,8.7847 9.8075,8.3947 L6.9785,5.5657 C6.5875,5.1747 5.9555,5.1747 5.5645,5.5657 C5.1735,5.9557 5.1735,6.5887 5.5645,6.9797 L8.3935,9.8087 Z M18.9995,5.9997 C19.5525,5.9997 19.9995,5.5527 19.9995,4.9997 L19.9995,0.9997 C19.9995,0.4477 19.5525,-0.0003 18.9995,-0.0003 C18.4475,-0.0003 17.9995,0.4477 17.9995,0.9997 L17.9995,4.9997 C17.9995,5.5527 18.4475,5.9997 18.9995,5.9997 L18.9995,5.9997 Z M28.8995,10.1017 C29.1555,10.1017 29.4115,10.0037 29.6065,9.8087 L32.4355,6.9797 C32.8265,6.5887 32.8265,5.9557 32.4355,5.5657 C32.0445,5.1747 31.4125,5.1747 31.0215,5.5657 L28.1925,8.3947 C27.8015,8.7847 27.8015,9.4177 28.1925,9.8087 C28.3875,10.0037 28.6435,10.1017 28.8995,10.1017 L28.8995,10.1017 Z M9.0025,17.9637 C9.0705,17.9777 9.1375,17.9847 9.2045,17.9847 C9.6695,17.9847 10.0855,17.6577 10.1825,17.1847 C11.0355,13.0217 14.7435,9.9997 18.9995,9.9997 C20.9685,10.0007 22.8375,10.6247 24.4055,11.8047 C24.8475,12.1377 25.4745,12.0477 25.8055,11.6077 C26.1385,11.1657 26.0495,10.5387 25.6075,10.2067 C23.6905,8.7637 21.4055,8.0007 18.9995,7.9997 C13.7975,7.9997 9.2655,11.6947 8.2235,16.7837 C8.1125,17.3247 8.4615,17.8537 9.0025,17.9637 L9.0025,17.9637 Z M30.9995,49.9997 L40.9625,49.9997 C44.8225,49.9997 47.9625,46.8597 47.9625,42.9997 C47.9625,39.1407 44.8225,35.9997 40.9625,35.9997 C37.1025,35.9997 33.9625,39.1407 33.9625,42.9997 C33.9625,43.5527 34.4105,43.9997 34.9625,43.9997 C35.5155,43.9997 35.9625,43.5527 35.9625,42.9997 C35.9625,40.2427 38.2065,37.9997 40.9625,37.9997 C43.7195,37.9997 45.9625,40.2427 45.9625,42.9997 C45.9625,45.7567 43.7195,47.9997 40.9625,47.9997 L30.9995,47.9997 C30.4475,47.9997 29.9995,48.4477 29.9995,48.9997 C29.9995,49.5527 30.4475,49.9997 30.9995,49.9997 L30.9995,49.9997 Z M57.9625,37.9997 C57.9625,40.5617 56.9955,42.9977 55.2375,44.8607 C54.8585,45.2627 54.8765,45.8957 55.2785,46.2747 C55.4715,46.4557 55.7185,46.5467 55.9645,46.5467 C56.2305,46.5467 56.4955,46.4417 56.6925,46.2337 C58.8015,43.9977 59.9625,41.0737 59.9625,37.9997 C59.9625,34.1097 58.0625,30.4437 54.8795,28.1937 C54.4285,27.8727 53.8045,27.9827 53.4865,28.4327 C53.1675,28.8837 53.2745,29.5077 53.7255,29.8257 C56.3785,31.7017 57.9625,34.7577 57.9625,37.9997 L57.9625,37.9997 Z M53.9625,47.9997 L48.9625,47.9997 C48.4105,47.9997 47.9625,48.4477 47.9625,48.9997 C47.9625,49.5527 48.4105,49.9997 48.9625,49.9997 L53.9625,49.9997 C56.1685,49.9997 57.9625,51.7937 57.9625,53.9997 C57.9625,56.2057 56.1685,57.9997 53.9625,57.9997 C52.8805,57.9997 51.8665,57.5737 51.1075,56.8007 C50.7205,56.4067 50.0865,56.4007 49.6935,56.7867 C49.2985,57.1737 49.2925,57.8067 49.6795,58.2007 C50.8175,59.3617 52.3385,59.9997 53.9625,59.9997 C57.2715,59.9997 59.9625,57.3087 59.9625,53.9997 C59.9625,50.6917 57.2715,47.9997 53.9625,47.9997 L53.9625,47.9997 Z M43.9625,51.9997 L36.9995,51.9997 C36.4475,51.9997 35.9995,52.4477 35.9995,52.9997 C35.9995,53.5527 36.4475,53.9997 36.9995,53.9997 L43.9625,53.9997 C45.0655,53.9997 45.9625,54.8977 45.9625,55.9997 C45.9625,57.1027 45.0655,57.9997 43.9625,57.9997 C43.4275,57.9997 42.9245,57.7917 42.5475,57.4137 C42.1575,57.0227 41.5245,57.0237 41.1335,57.4117 C40.7425,57.8027 40.7415,58.4357 41.1325,58.8257 C41.8875,59.5827 42.8925,59.9997 43.9625,59.9997 C46.1685,59.9997 47.9625,58.2057 47.9625,55.9997 C47.9625,53.7937 46.1685,51.9997 43.9625,51.9997 L43.9625,51.9997 Z M8.9995,47.9997 L7.9995,47.9997 C4.6915,47.9997 1.9995,45.3087 1.9995,41.9997 C1.9995,38.6917 4.6915,35.9997 7.9995,35.9997 C8.5525,35.9997 8.9995,35.5527 8.9995,34.9997 C8.9995,34.4477 8.5525,33.9997 7.9995,33.9997 C3.5885,33.9997 -0.0005,37.5887 -0.0005,41.9997 C-0.0005,46.4107 3.5885,49.9997 7.9995,49.9997 L8.9995,49.9997 C10.8185,49.9997 12.1305,50.5547 13.0515,53.3167 C13.1905,53.7357 13.5815,53.9997 13.9995,53.9997 C14.1045,53.9997 14.2115,53.9837 14.3165,53.9487 C14.8405,53.7747 15.1235,53.2077 14.9485,52.6837 C13.8695,49.4447 12.0345,47.9997 8.9995,47.9997 L8.9995,47.9997 Z M22.7065,17.0927 C22.3985,17.5517 22.5205,18.1727 22.9795,18.4807 C23.4385,18.7887 24.0595,18.6657 24.3675,18.2077 C26.9775,14.3207 31.3125,11.9997 35.9625,11.9997 C43.6825,11.9997 49.9625,18.2807 49.9625,25.9997 C49.9625,27.2687 49.7935,28.5247 49.4595,29.7337 C49.3125,30.2667 49.6255,30.8177 50.1575,30.9637 C50.2465,30.9887 50.3365,30.9997 50.4245,30.9997 C50.8625,30.9997 51.2655,30.7087 51.3875,30.2667 C51.7695,28.8837 51.9625,27.4487 51.9625,25.9997 C51.9625,17.1777 44.7855,9.9997 35.9625,9.9997 C30.6445,9.9997 25.6895,12.6517 22.7065,17.0927 L22.7065,17.0927 Z M24.6525,23.1347 C24.2535,23.5157 23.6205,23.5007 23.2395,23.1017 C21.3325,21.1017 18.7615,19.9997 15.9995,19.9997 C10.4855,19.9997 5.9995,24.4867 5.9995,29.9997 C5.9995,30.6157 6.0555,31.2297 6.1655,31.8257 C6.2665,32.3687 5.9075,32.8907 5.3645,32.9907 C5.3025,33.0027 5.2415,33.0077 5.1815,33.0077 C4.7085,33.0077 4.2885,32.6707 4.1995,32.1897 C4.0665,31.4737 3.9995,30.7377 3.9995,29.9997 C3.9995,23.3827 9.3835,17.9997 15.9995,17.9997 C19.3135,17.9997 22.3985,19.3217 24.6865,21.7207 C25.0675,22.1207 25.0525,22.7537 24.6525,23.1347 L24.6525,23.1347 Z" id="crazy-weather"> </path> </g> </g> </g></svg>`,
  "Climate Change": html`<svg fill="#000000" width="35px" height="35px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512.00 512.00" xml:space="preserve" stroke="#000000" stroke-width="0.00512"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <g> <g> <path d="M156.834,38.554C188.041,24.294,221.406,17.067,256,17.067c17.289,0,34.475,1.843,51.191,5.495 c-0.759,14.362,5.291,23.962,9.515,30.66c1.186,1.886,2.807,4.463,2.978,5.171c0,35.251-7.134,42.667-8.533,42.667 c-15.36,0-41.566,14.319-51.081,32.094c-5.828,10.872-5.359,22.374,1.314,32.375c4.813,7.219,8.934,15.215,12.928,22.938 c8.218,15.915,17.331,33.579,31.343,33.579c2.884,0,5.973-0.751,9.31-2.415c11.136-5.572,19.302-21.769,27.204-37.427 c3.763-7.458,9.336-18.509,12.484-21.325c11.204,1.109,16.358,10.556,23.356,25.711c4.787,10.368,9.737,21.094,19.243,25.848 c16.478,8.218,70.844-0.538,100.983-13.338c0.358-0.154,0.597-0.444,0.922-0.631c0.495-0.299,0.973-0.58,1.399-0.956 c0.41-0.375,0.734-0.794,1.058-1.237c0.324-0.427,0.631-0.853,0.87-1.34c0.247-0.495,0.384-0.998,0.529-1.536 c0.137-0.521,0.265-1.024,0.307-1.579c0.034-0.572-0.034-1.118-0.111-1.698c-0.051-0.375,0.026-0.734-0.077-1.109 c-20.659-76.399-76.791-139.955-150.161-170.001c-4.36-1.783-9.344,0.299-11.127,4.659c-1.783,4.361,0.299,9.344,4.659,11.128 c66.116,27.085,117.146,83.345,137.95,151.364c-31.795,11.546-72.166,14.711-79.573,10.999 c-4.147-2.074-7.825-10.027-11.375-17.724c-6.758-14.635-16.009-34.671-39.313-35.703c-11.52-0.41-18.099,12.612-27.264,30.78 c-5.7,11.315-13.517,26.812-19.593,29.85c-4.42,2.227-11.58-11.554-17.86-23.723c-4.011-7.765-8.55-16.572-13.892-24.576 c-3.191-4.779-3.336-9.506-0.469-14.865c7.134-13.329,27.93-23.074,36.036-23.074c16.99,0,25.6-20.096,25.6-59.733 c0-5.367-2.722-9.685-5.606-14.268c-4.343-6.878-8.823-13.995-6.135-26.274c0.99-4.506-1.784-8.969-6.246-10.103 C298.377,2.611,277.257,0,256,0c-37.06,0-72.806,7.748-106.257,23.023c-4.284,1.963-6.17,7.023-4.215,11.307 C147.49,38.622,152.55,40.516,156.834,38.554z"></path> <path d="M375.117,262.46c-3.132,0.896-7.031,2.014-8.183,2.074c-13.03,0-21.129,9.882-27.622,17.826 c-2.978,3.644-7.492,9.148-9.719,9.148c-0.367,0-0.896-0.162-1.51-0.469c-4.284-2.15-8.772-3.226-13.355-3.226 c-11.042,0-20.591,6.502-22.707,15.471c-1.468,6.229,0.742,14.771,11.366,20.087c16.171,8.081,32.896,16.444,40.448,23.996 c4.83,4.83,13.278,7.603,23.185,7.603c15.138,0,35.251-7.339,42.146-28.006c2.91-8.73,10.069-15.582,16.384-21.623 c7.33-7.023,14.259-13.653,14.362-22.869c0.06-5.402-2.364-10.598-7.211-15.437c-6.69-6.69-15.846-10.086-27.204-10.086 C394.419,256.947,383.266,260.13,375.117,262.46z M422.844,282.283c-0.017,2.039-5.478,7.27-9.097,10.726 c-7.364,7.049-16.529,15.812-20.779,28.561c-4.011,12.041-16.034,16.333-25.95,16.333c-6.434,0-10.266-1.749-11.119-2.603 c-9.515-9.515-26.692-18.108-44.885-27.196c-0.998-0.503-1.647-0.973-2.031-1.306c1.374-1.331,6.699-2.884,11.469-0.495 c3.012,1.502,6.093,2.27,9.139,2.27c10.317-0.008,17.015-8.183,22.929-15.403c5.717-6.989,9.805-11.571,14.413-11.571 c3.328,0,7.33-1.143,12.877-2.731c7.177-2.048,16.998-4.855,25.685-4.855c6.758,0,11.716,1.664,15.138,5.086 C422.46,280.926,422.852,282.018,422.844,282.283z"></path> <path d="M215.834,364.433c1.664,1.664,3.849,2.5,6.033,2.5c2.185,0,4.369-0.836,6.033-2.5 c9.481-9.481,13.73-20.693,11.964-31.573c-1.442-8.858-7.006-16.905-14.182-20.497c-3.072-1.527-7.1-2.705-11.767-4.062 c-8.431-2.458-21.171-6.17-24.329-12.194c-0.649-1.246-1.348-3.371,0.034-7.543c2.517-7.544,4.804-11.836,6.81-15.625 c5.504-10.334,8.371-17.101,8.371-46.805c0-15.625-7.501-27.733-21.137-34.082c-4.258-1.971-9.336-0.137-11.332,4.139 c-1.988,4.275-0.137,9.344,4.13,11.341c7.484,3.482,11.273,9.737,11.273,18.603c0,26.829-2.398,31.326-6.366,38.784 c-2.21,4.164-4.975,9.344-7.936,18.253c-2.551,7.654-2.202,14.669,1.041,20.855c6.528,12.467,22.793,17.203,34.671,20.659 c3.55,1.033,7.211,2.099,8.909,2.953c1.604,0.802,4.25,3.576,4.966,7.953c0.87,5.402-1.613,11.204-7.185,16.777 C212.497,355.703,212.497,361.097,215.834,364.433z"></path> <path d="M93.867,452.267c0,4.71,3.823,8.533,8.533,8.533c28.237,0,51.2-22.963,51.2-51.2c0-4.71-3.823-8.533-8.533-8.533 c-4.71,0-8.533,3.823-8.533,8.533c0,18.825-15.309,34.133-34.133,34.133C97.69,443.733,93.867,447.556,93.867,452.267z"></path> <path d="M509.568,220.57c-0.64-4.668-5.001-7.936-9.626-7.279c-4.668,0.64-7.927,4.949-7.279,9.626 c1.51,10.871,2.27,22.008,2.27,33.084c0,131.746-107.187,238.933-238.933,238.933c-37.026,0-56.047-7.714-56.405-7.859 c-4.309-1.826-9.327,0.171-11.17,4.497c-1.86,4.335,0.154,9.353,4.48,11.204C193.783,503.151,214.904,512,256,512 c141.158,0,256-114.842,256-256C512,244.139,511.181,232.218,509.568,220.57z"></path> <path d="M153.6,320.998V85.333c0-28.237-22.963-51.2-51.2-51.2c-28.237,0-51.2,22.963-51.2,51.2v8.533 c0,4.71,3.823,8.533,8.533,8.533s8.533-3.823,8.533-8.533v-8.533c0-18.825,15.309-34.133,34.133-34.133 c18.825,0,34.133,15.309,34.133,34.133v240.725c0,3.209,1.792,6.144,4.642,7.603c28.723,14.694,46.558,43.793,46.558,75.938 c0,47.053-38.281,85.333-85.333,85.333S17.067,456.653,17.067,409.6c0-32.145,17.835-61.244,46.558-75.938 c2.85-1.459,4.642-4.395,4.642-7.603v-35.925H76.8c4.71,0,8.533-3.823,8.533-8.533s-3.823-8.533-8.533-8.533h-8.533v-34.133H76.8 c4.71,0,8.533-3.823,8.533-8.533s-3.823-8.533-8.533-8.533h-8.533v-34.133H76.8c4.71,0,8.533-3.823,8.533-8.533 s-3.823-8.533-8.533-8.533h-8.533v-34.133h42.667c4.71,0,8.533-3.823,8.533-8.533s-3.823-8.533-8.533-8.533h-51.2 c-4.71,0-8.533,3.823-8.533,8.533v192.998C19.49,339.302,0,372.787,0,409.6C0,466.065,45.935,512,102.4,512 c56.465,0,102.4-45.935,102.4-102.4C204.8,372.787,185.31,339.302,153.6,320.998z"></path> <path d="M258.884,460.143c9.02,0,17.442-3.243,23.1-8.9c12.988-12.988,2.825-34.833-8.533-46.199 c-2.603-2.603-6.016-3.977-9.873-3.977c-11.81,0-25.745,13.764-30.865,26.129c-3.908,9.429-2.782,18.193,3.072,24.047 C241.442,456.9,249.865,460.143,258.884,460.143z M248.192,434.475c2.697-7.424,10.65-14.635,14.404-16.085 c6.562,7.296,10.359,17.749,7.322,20.787c-4.89,4.89-17.186,4.881-22.067,0C247.108,438.434,247.569,436.173,248.192,434.475z"></path> </g> </g> </g> </g></svg>`,
  Drought: html`<svg fill="#000000" width="35px" height="35px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 351.338 351.338" xml:space="preserve"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path d="M346.338,154.251c0,0-46.439,0-61.919,0c-4,0-4.128-3.5-4.128-3.5V72.772c0-2.188,0.644-2.107,1.002-0.926 c0.358,1.182,0.767,2.428,1.229,3.744c1.37,3.894,6.389,17.077,13.433,23.232c7.339,6.416,22.624,9.877,33.28,9.877 c6.971,0,11.484-1.45,14.205-4.563c3.74-4.28,3.943-12.301,0.602-23.837c-1.38-4.763-5.332-16.49-12.221-22.511 c-8.685-7.593-29.498-11.403-38.708-11.403c-1.03,0-4.224,0.001-4.734,0.001c-12.73,0-23.088,10.357-23.088,23.088V151 c0,0,0.544,3.251-4.289,3.251c-5.437,0-15.24,0-21.75,0c-3.583,0-3.461-2.499-3.461-2.499V43.036 c0-13.453-10.944-24.399-24.396-24.399c-0.542,0-4.003-0.001-5.131-0.001c-11.517,0-32.892,4.642-41.543,12.204 c-10.166,8.885-20.901,39.777-12.535,49.351c2.821,3.227,7.564,4.729,14.927,4.729h0.001c11.435,0,27.818-3.697,35.657-10.549 c7.519-6.572,12.906-20.734,14.379-24.918c1.371-3.895,3.642-7.716,3.642-6.418v108.383c0,0,0.461,2.832-4.706,2.832 c-62.229,0-57.522,0-74.791,0c-4.458,0-4.31-3.166-4.31-3.166V75.817c0-10.946-8.905-19.853-19.851-19.853 c-0.412,0-24.798,0.787-35.444,9.419c-5.951,4.824-9.022,14.67-10.154,18.575c-4.227,14.594-0.443,18.923,0.8,20.345 c2.474,2.829,6.423,4.147,12.429,4.147h0.001c6.96,0,20.551-2.229,27.392-8.209c3.67-3.208,6.608-8.484,8.621-12.927 c0.449-0.992,1.207-1.855,1.207,1.895v61.875c0,0-0.315,3.166-3.653,3.166c-27.823,0-113.331,0-113.331,0c-2.75,0-5,2.25-5,5 v162.154c0,2.75,2.25,5,5,5h5c2.75,0,5-2.25,5-5V174.251c0-2.75,2.025-5,4.501-5s6.514,1.007,8.973,2.236l11.746,5.874 c2.459,1.229,3.001,3.939,1.203,6.02l-9.456,10.948c-1.798,2.081-1.183,4.628,1.367,5.659l67.604,27.338 c2.55,1.03,3.782,3.764,2.739,6.074c-1.044,2.311-4.09,4.703-6.771,5.319l-28.684,6.586c-2.681,0.616-6.419,2.754-8.308,4.753 L33.277,278.24c-1.889,1.999-2.282,5.566-0.875,7.929l21.771,36.529c1.407,2.362,4.492,3.143,6.854,1.735l4.295-2.56 c2.362-1.407,3.143-4.492,1.735-6.855l-15.965-26.787c-1.407-2.362-1.014-5.93,0.875-7.929l15.727-16.64 c1.889-1.998,5.627-4.137,8.308-4.753l31.51-7.234c2.681-0.616,5.799-3.17,6.931-5.676l9.166-20.295 c1.133-2.506-0.027-5.4-2.577-6.431l-62.652-25.336c-2.55-1.031-3.165-3.578-1.368-5.659l8.367-9.688 c1.798-2.081,1.256-4.791-1.203-6.02l-2.166-1.083c-2.459-1.23-2.222-2.236,0.528-2.236h161.236c2.75,0,5.363,2.221,5.808,4.935 l5.413,33.084c0.444,2.714,2.949,5.626,5.565,6.471l62.949,20.317c2.616,0.845,3.293,3.244,1.503,5.332l-8.374,9.766 c-1.79,2.088-3.181,6.045-3.09,8.793l0.38,11.543c0.091,2.748-2.074,5.213-4.811,5.477l-24.792,2.391 c-2.737,0.264-6.763,1.848-8.946,3.519l-37.49,28.7c-2.184,1.672-1.779,3.551,0.898,4.177l80.502,18.816 c2.678,0.626,5.381-1.054,6.006-3.732l1.139-4.867c0.625-2.678-1.053-5.381-3.73-6.008l-49.596-11.592 c-2.678-0.627-3.082-2.506-0.898-4.178l8.88-6.798c2.184-1.672,6.21-3.255,8.947-3.518l34.536-3.33 c2.737-0.264,4.902-2.729,4.811-5.477l-0.651-19.787c-0.091-2.748,1.3-6.705,3.09-8.793l19.253-22.451 c1.79-2.088,1.113-4.487-1.503-5.332l-75.688-24.429c-2.616-0.845-5.121-3.757-5.565-6.471l-3.538-21.623 c-0.444-2.714,1.442-4.935,4.192-4.935h82.363c2.75,0,5,2.25,5,5v147.154c0,2.75,2.25,5,5,5h5c2.75,0,5-2.25,5-5V159.251 C351.338,156.501,349.088,154.251,346.338,154.251z M331.414,93.616c-1.891,1.569-21.959-2.915-25.588-6.087 c-4.772-4.17-13.095-24.882-11.69-26.126c1.283-1.137,23.928,4.283,27.814,7.68C326.76,73.287,332.731,92.522,331.414,93.616z M192.898,63.079c-4.098,3.581-27.396,8.422-28.812,6.688c-1.168-1.432,4.94-22.769,10.505-27.632 c4.489-3.924,30.39-9.641,31.305-8.496C207.252,35.335,198.403,58.266,192.898,63.079z M102.284,88.948 c-5.222,4.566-16.854,5.459-17.551,4.503c-0.889-1.221,3.845-14.167,6.827-16.773c2.571-2.247,18.056-7.359,19.081-5.577 C111.442,72.492,105.43,86.199,102.284,88.948z"></path> <path d="M238.781,258.366l-16.425-32.852c-1.23-2.46-4.224-3.417-6.652-2.127l-32.053,17.028c-2.428,1.29-5.995,0.744-7.926-1.214 l-18.326-18.58c-1.931-1.958-5.112-1.98-7.07-0.049l-3.561,3.512c-1.958,1.931-1.979,5.112-0.049,7.07l26.174,26.537 c1.931,1.958,5.498,2.504,7.926,1.214l28.344-15.058c2.429-1.29,5.422-0.334,6.652,2.126l3.089,6.178 c1.229,2.46,0.263,5.553-2.149,6.874l-69.004,37.797c-2.412,1.32-4.749,4.622-5.193,7.336l-2.636,16.1 c-0.444,2.714,1.413,5.298,4.127,5.742l4.934,0.809c2.714,0.444,5.298-1.413,5.742-4.127l1.454-8.881 c0.444-2.714,2.781-6.016,5.193-7.337l75.26-41.224C239.044,263.92,240.011,260.826,238.781,258.366z"></path> </g> </g></svg>`,
  "Temperature increase": html`<svg width="35px" height="35px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M18 3V21M18 3L15 6M18 3L21 6M7 15.9998C6.44772 15.9998 6 16.4475 6 16.9998C6 17.5521 6.44772 17.9998 7 17.9998C7.55228 17.9998 8 17.5521 8 16.9998C8 16.4475 7.55228 15.9998 7 15.9998ZM7 15.9998V11.9998M7 16.9998L7.00707 17.0069M11 16.9998C11 19.209 9.20914 20.9998 7 20.9998C4.79086 20.9998 3 19.209 3 16.9998C3 15.9854 3.37764 15.0591 4 14.354L4 6C4 4.34315 5.34315 3 7 3C8.65685 3 10 4.34315 10 6V14.354C10.6224 15.0591 11 15.9854 11 16.9998Z" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>`,
  "Heat Stress": html`<svg version="1.0" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="35px" width="35px"  viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M32,14.002c-9.941,0-18,8.059-18,18s8.059,18,18,18 s18-8.059,18-18S41.941,14.002,32,14.002z M32,48.002c-8.837,0-16-7.164-16-16s7.163-16,16-16s16,7.164,16,16 S40.837,48.002,32,48.002z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M32,20.002c-0.553,0-1,0.447-1,1s0.447,1,1,1 c5.522,0,10,4.477,10,10c0,0.553,0.447,1,1,1s1-0.447,1-1C44,25.375,38.627,20.002,32,20.002z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M63,31H53c-0.553,0-1,0.447-1,1s0.447,1,1,1h10 c0.553,0,1-0.447,1-1S63.553,31,63,31z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M11.457,36.47l-3.863,1.035c-0.534,0.144-0.851,0.692-0.707,1.226 c0.143,0.533,0.69,0.85,1.225,0.706l3.863-1.035c0.533-0.143,0.85-0.69,0.707-1.225C12.539,36.644,11.99,36.327,11.457,36.47z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M49.32,22c0.277,0.479,0.888,0.643,1.367,0.366l8.66-5 c0.479-0.276,0.643-0.888,0.365-1.366c-0.275-0.479-0.887-0.642-1.365-0.365l-8.66,5C49.208,20.912,49.045,21.521,49.32,22z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M17.858,46.143c-0.39-0.391-1.023-0.389-1.414,0l-2.828,2.828 c-0.391,0.391-0.39,1.025,0.001,1.415c0.39,0.391,1.022,0.39,1.413-0.001l2.828-2.828C18.249,47.168,18.249,46.534,17.858,46.143z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M42,14.68c0.479,0.276,1.09,0.113,1.367-0.366l5-8.66 C48.644,5.175,48.48,4.563,48,4.287c-0.478-0.276-1.088-0.112-1.365,0.366l-4.999,8.661C41.358,13.793,41.522,14.403,42,14.68z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M26.824,51.318c-0.532-0.143-1.08,0.176-1.225,0.707l-1.035,3.863 c-0.143,0.535,0.176,1.083,0.709,1.226c0.533,0.144,1.08-0.173,1.223-0.708l1.035-3.863C27.676,52.012,27.359,51.463,26.824,51.318 z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M32,12c0.554,0,1.001-0.446,1.002-1V1c0-0.553-0.447-1-1.002-1 c-0.551,0-0.998,0.447-0.999,1l0.001,10C31.002,11.553,31.449,12,32,12z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M38.402,52.025c-0.141-0.532-0.689-0.85-1.225-0.707 c-0.533,0.143-0.848,0.692-0.707,1.225l1.035,3.863c0.144,0.535,0.693,0.85,1.227,0.707s0.849-0.689,0.705-1.225L38.402,52.025z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M20.637,14.312c0.275,0.479,0.887,0.643,1.363,0.367 c0.48-0.277,0.645-0.887,0.368-1.367l-5-8.66C17.092,4.174,16.48,4.01,16,4.287c-0.477,0.275-0.641,0.887-0.365,1.365 L20.637,14.312z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M47.558,46.142c-0.388-0.39-1.022-0.39-1.414,0 c-0.391,0.39-0.388,1.024,0,1.414l2.828,2.828c0.392,0.392,1.025,0.389,1.415-0.001c0.391-0.39,0.391-1.021-0.001-1.413 L47.558,46.142z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M4.654,17.365l8.662,4.999c0.477,0.276,1.088,0.113,1.363-0.364 c0.277-0.479,0.115-1.09-0.364-1.367l-8.661-5C5.176,15.356,4.564,15.52,4.287,16C4.013,16.477,4.176,17.089,4.654,17.365z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M52.027,38.4l3.863,1.035c0.535,0.145,1.082-0.176,1.225-0.709 c0.144-0.532-0.172-1.079-0.707-1.223l-3.863-1.035c-0.531-0.145-1.081,0.173-1.225,0.707C51.176,37.709,51.496,38.256,52.027,38.4 z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M12,32c0.001-0.554-0.445-1-0.998-1.002L1,31 c-0.552,0-1,0.445-1,1c0.001,0.551,0.448,1,1.001,1l10.001-0.002C11.553,32.998,12.001,32.552,12,32z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M52.545,27.529l3.863-1.035c0.535-0.143,0.85-0.693,0.706-1.227 c-0.142-0.531-0.688-0.848-1.224-0.705l-3.863,1.035c-0.533,0.141-0.85,0.691-0.707,1.225 C51.461,27.356,52.012,27.67,52.545,27.529z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M14.68,42c-0.275-0.48-0.886-0.644-1.365-0.368l-8.661,5.002 C4.176,46.91,4.01,47.52,4.287,48c0.277,0.477,0.889,0.641,1.367,0.365l8.66-5.002C14.791,43.088,14.957,42.479,14.68,42z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M46.144,17.856c0.389,0.392,1.022,0.388,1.414,0l2.828-2.828 c0.392-0.392,0.39-1.024-0.002-1.415c-0.388-0.39-1.021-0.391-1.412,0.001l-2.828,2.828C45.752,16.83,45.754,17.466,46.144,17.856z "></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M22,49.32c-0.479-0.277-1.088-0.113-1.365,0.364l-5,8.663 c-0.275,0.478-0.115,1.088,0.365,1.365c0.479,0.274,1.09,0.11,1.367-0.367l4.998-8.662C22.641,50.207,22.48,49.597,22,49.32z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M37.178,12.68c0.531,0.145,1.078-0.176,1.225-0.707l1.035-3.863 c0.143-0.535-0.176-1.083-0.709-1.225c-0.531-0.144-1.08,0.172-1.223,0.707l-1.035,3.863C36.324,11.986,36.645,12.536,37.178,12.68 z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M32,52c-0.553-0.002-0.998,0.446-1,0.998l0.002,10.004 C31.002,63.552,31.445,64,32,64c0.553,0,1-0.449,1.001-1l-0.003-10.002C32.998,52.447,32.555,52,32,52z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M25.6,11.973c0.139,0.533,0.691,0.85,1.225,0.707 c0.532-0.141,0.846-0.691,0.707-1.225l-1.035-3.863c-0.145-0.535-0.693-0.851-1.227-0.706c-0.531,0.142-0.85,0.688-0.705,1.224 L25.6,11.973z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M43.363,49.687c-0.275-0.478-0.883-0.644-1.363-0.365 c-0.479,0.274-0.641,0.885-0.367,1.364l5.004,8.661c0.275,0.478,0.883,0.644,1.363,0.366c0.479-0.277,0.642-0.889,0.367-1.367 L43.363,49.687z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M16.443,17.856c0.387,0.394,1.023,0.39,1.414,0 c0.391-0.388,0.387-1.021,0-1.414l-2.828-2.828c-0.393-0.392-1.025-0.39-1.415,0.002c-0.39,0.388-0.392,1.021,0.001,1.412 L16.443,17.856z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M59.348,46.633l-8.663-4.997 c-0.478-0.276-1.087-0.116-1.363,0.366c-0.278,0.477-0.112,1.086,0.364,1.364l8.664,4.999c0.477,0.275,1.086,0.115,1.363-0.365 C59.988,47.521,59.824,46.91,59.348,46.633z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#231F20" d="M11.974,25.599L8.11,24.563c-0.536-0.144-1.083,0.175-1.225,0.708 c-0.144,0.531,0.171,1.08,0.707,1.225l3.863,1.034c0.531,0.146,1.081-0.175,1.225-0.707C12.825,26.293,12.505,25.746,11.974,25.599 z"></path> </g> </g></svg>`,
  "Rainfall Variability": html`<svg width="35px" height="35px" viewBox="0 0 24 24" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><defs><style>.cls-1{fill:none;stroke:#020202;stroke-miterlimit:10;stroke-width:1.91px;}</style></defs><path class="cls-1" d="M3.41,20.07a3.83,3.83,0,0,1,1.92-7.14,4.78,4.78,0,0,1,9.56,0,5.9,5.9,0,0,1-.09,1h.57a3.34,3.34,0,0,1,1.43,6.36"></path><line class="cls-1" x1="10.59" y1="17.72" x2="8.2" y2="22.5"></line><line class="cls-1" x1="14.41" y1="17.72" x2="12.02" y2="22.5"></line><line class="cls-1" x1="6.78" y1="17.69" x2="4.37" y2="22.5"></line><path class="cls-1" d="M16.51,14.1a4.79,4.79,0,1,0-7-5.91"></path><line class="cls-1" x1="13.93" y1="0.5" x2="13.93" y2="2.41"></line><line class="cls-1" x1="23.5" y1="10.07" x2="21.59" y2="10.07"></line><line class="cls-1" x1="20.7" y1="3.3" x2="19.35" y2="4.65"></line><line class="cls-1" x1="8.52" y1="4.65" x2="7.17" y2="3.3"></line></g></svg>`,
  Flood: html`<svg fill="#000000" width="37px" height="37px" viewBox="-3.2 -3.2 38.40 38.40" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="0.05"></g><g id="SVGRepo_iconCarrier"> <defs> <style> .cls-1 { fill: none; } </style> </defs> <path d="M29,28a2.8828,2.8828,0,0,1-1-.1816v-.0059a3.7662,3.7662,0,0,1-2.0532-2.1338A.971.971,0,0,0,25,25a1.007,1.007,0,0,0-.9487.6836A3.4376,3.4376,0,0,1,21,28a3.44,3.44,0,0,1-3.0532-2.3213A.9894.9894,0,0,0,17,25a1.007,1.007,0,0,0-.9487.6836A3.4376,3.4376,0,0,1,13,28a3.44,3.44,0,0,1-3.0532-2.3213,1,1,0,0,0-1.8955.0049A3.4376,3.4376,0,0,1,5,28H2v2H5a4.9316,4.9316,0,0,0,4-1.9873,5.0192,5.0192,0,0,0,8,0,5.0192,5.0192,0,0,0,8,0,5.1433,5.1433,0,0,0,2.1379,1.62A4.8374,4.8374,0,0,0,29,30h1V28Z" transform="translate(0 0)"></path> <path d="M28,13.63,29.7573,15,31,13.4282,16.6123,2.2139a1.0094,1.0094,0,0,0-1.2427,0L1,13.4194l1.2427,1.5718L4,13.6211v5.1875a3.6907,3.6907,0,0,1-2,2.0039V22.896a4.9958,4.9958,0,0,0,3-1.8833,5.0192,5.0192,0,0,0,8,0,5.0192,5.0192,0,0,0,8,0A4.9316,4.9316,0,0,0,25,23h5V21H28Zm-6.0513,5.0532a1,1,0,0,0-1.8955-.0049A3.44,3.44,0,0,1,17,21a3.4376,3.4376,0,0,1-3.0513-2.3164A1.007,1.007,0,0,0,13,18a.9894.9894,0,0,0-.9468.6787A3.44,3.44,0,0,1,9,21a3.37,3.37,0,0,1-3.0021-2.19L6,12.0615l9.991-7.79L26,12.0718,26.0017,21H25A3.4376,3.4376,0,0,1,21.9487,18.6836Z" transform="translate(0 0)"></path> <rect id="_Transparent_Rectangle_" data-name="<Transparent Rectangle>" class="cls-1" width="32" height="32"></rect> </g></svg>`,
  "Multiple Risks": html`<svg height="35px" width="35px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 54.264 54.264" xml:space="preserve" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <g> <g> <path style="fill:#010002;" d="M52.021,49.561c-0.011-0.001-0.02-0.001-0.029,0H2.244c-0.813,0-1.563-0.439-1.959-1.15 c-0.397-0.71-0.378-1.579,0.049-2.271L25.207,5.769c0.408-0.663,1.132-1.066,1.911-1.066c0.777,0,1.502,0.403,1.91,1.066 l24.704,40.098c0.332,0.392,0.532,0.897,0.532,1.451C54.265,48.556,53.261,49.561,52.021,49.561z M6.263,45.073h41.709 L27.118,11.224L6.263,45.073z"></path> </g> <g> <path style="fill:#010002;" d="M27.116,38.89c0.584,0,1.082,0.205,1.492,0.612c0.408,0.412,0.613,0.907,0.613,1.49 c0,0.586-0.217,1.081-0.648,1.493c-0.434,0.406-0.919,0.612-1.457,0.612c-0.537,0-1.022-0.206-1.455-0.612 c-0.432-0.412-0.646-0.907-0.646-1.493c0-0.583,0.203-1.078,0.613-1.49C26.036,39.094,26.532,38.89,27.116,38.89z M28.589,35.945 h-2.944V18.062h2.944V35.945z"></path> </g> </g> </g> </g></svg>`,
});
```

#style

<style>
/* Tooltip Styling */
  .plotTooltip {
    padding: 10px 10px;
    color: black;
    border-radius: 4px;
    border: 1px solid rgba(0, 0, 0, 1);
    pointer-events: none;
    transform: translate(-50%, -100%);
    font-family: "IBM Plex Sans", "Source Serif Pro";
    font-size: 14px;
    background: rgba(255, 255, 255, 1);
    transition: 0.3s opacity ease-out, 0.1s border-color ease-out;
    position: relative;
  }

  .plotTooltip::before {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: black transparent transparent transparent;
  }

  .plotTooltip::after {
    content: "";
    position: absolute;
    top: calc(100% - 1px);
    left: 50%;
    margin-left: -4.9px;
    border-width: 4.9px;
    border-style: solid;
    border-color: white transparent transparent transparent;
  }
  /* Button Style */
.atlas_button {
  background: #FFFFFF;
  border: 1px solid black;
  padding: 10px 20px;
}

.atlas_button:hover {
  background: #EFEFEF;
}
</style>
